[supervisord]
nodaemon=true
loglevel=warn
silent=false
logfile=/dev/stdout
logfile_maxbytes=0
user=root

[program:go]
command=/app/main
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stderr_events_enabled=false
autorestart=true
priority=10

[program:python]
command=sh -c "if [ -d python_app ]; then cd python_app && . .venv/bin/activate && python -m app.server; else sleep 1d; fi"
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stderr_events_enabled=false
autorestart=true
priority=20
