// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: proto/v1/canvas.proto

package canvasv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Components    map[string]string      `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_proto_v1_canvas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{0}
}

func (x *HealthStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthStatus) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

type ChunkingConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// fixed to "sentence" for this phase
	Type           string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                            // "sentence"
	TargetTokens   int32  `protobuf:"varint,2,opt,name=target_tokens,json=targetTokens,proto3" json:"target_tokens,omitempty"`       // default 300
	OverlapPercent int32  `protobuf:"varint,3,opt,name=overlap_percent,json=overlapPercent,proto3" json:"overlap_percent,omitempty"` // default 10
	Tokenizer      string `protobuf:"bytes,4,opt,name=tokenizer,proto3" json:"tokenizer,omitempty"`                                  // e.g., "tiktoken:cl100k_base"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChunkingConfig) Reset() {
	*x = ChunkingConfig{}
	mi := &file_proto_v1_canvas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkingConfig) ProtoMessage() {}

func (x *ChunkingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkingConfig.ProtoReflect.Descriptor instead.
func (*ChunkingConfig) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkingConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChunkingConfig) GetTargetTokens() int32 {
	if x != nil {
		return x.TargetTokens
	}
	return 0
}

func (x *ChunkingConfig) GetOverlapPercent() int32 {
	if x != nil {
		return x.OverlapPercent
	}
	return 0
}

func (x *ChunkingConfig) GetTokenizer() string {
	if x != nil {
		return x.Tokenizer
	}
	return ""
}

type SpatialCoordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             int32                  `protobuf:"varint,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpatialCoordinates) Reset() {
	*x = SpatialCoordinates{}
	mi := &file_proto_v1_canvas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpatialCoordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpatialCoordinates) ProtoMessage() {}

func (x *SpatialCoordinates) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpatialCoordinates.ProtoReflect.Descriptor instead.
func (*SpatialCoordinates) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{2}
}

func (x *SpatialCoordinates) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SpatialCoordinates) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SpatialCoordinates) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                             // optional client-generated id or empty.
	SequenceIndex int32                  `protobuf:"varint,2,opt,name=sequence_index,json=sequenceIndex,proto3" json:"sequence_index,omitempty"` // the ordinal sequence of the chunk within the document
	StartPosition int64                  `protobuf:"varint,3,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"` // character offset in original content
	EndPosition   int64                  `protobuf:"varint,4,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`       // character offset in original content (exclusive)
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                                   // normalized chunk text
	Location      *SpatialCoordinates    `protobuf:"bytes,10,opt,name=location,proto3" json:"location,omitempty"`                                // optional 3D spatial coordinates for the chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_proto_v1_canvas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{3}
}

func (x *Chunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chunk) GetSequenceIndex() int32 {
	if x != nil {
		return x.SequenceIndex
	}
	return 0
}

func (x *Chunk) GetStartPosition() int64 {
	if x != nil {
		return x.StartPosition
	}
	return 0
}

func (x *Chunk) GetEndPosition() int64 {
	if x != nil {
		return x.EndPosition
	}
	return 0
}

func (x *Chunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Chunk) GetLocation() *SpatialCoordinates {
	if x != nil {
		return x.Location
	}
	return nil
}

type EmbeddingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // e.g., openai, local
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingConfig) Reset() {
	*x = EmbeddingConfig{}
	mi := &file_proto_v1_canvas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingConfig) ProtoMessage() {}

func (x *EmbeddingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingConfig.ProtoReflect.Descriptor instead.
func (*EmbeddingConfig) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{4}
}

func (x *EmbeddingConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *EmbeddingConfig) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *EmbeddingConfig) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

type EmbedQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Config        *EmbeddingConfig       `protobuf:"bytes,10,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedQueryRequest) Reset() {
	*x = EmbedQueryRequest{}
	mi := &file_proto_v1_canvas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedQueryRequest) ProtoMessage() {}

func (x *EmbedQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedQueryRequest.ProtoReflect.Descriptor instead.
func (*EmbedQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{5}
}

func (x *EmbedQueryRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EmbedQueryRequest) GetConfig() *EmbeddingConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type EmbedQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Dims          int32                  `protobuf:"varint,2,opt,name=dims,proto3" json:"dims,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedQueryResponse) Reset() {
	*x = EmbedQueryResponse{}
	mi := &file_proto_v1_canvas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedQueryResponse) ProtoMessage() {}

func (x *EmbedQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedQueryResponse.ProtoReflect.Descriptor instead.
func (*EmbedQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{6}
}

func (x *EmbedQueryResponse) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *EmbedQueryResponse) GetDims() int32 {
	if x != nil {
		return x.Dims
	}
	return 0
}

func (x *EmbedQueryResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *EmbedQueryResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

// ===== Combined Chunk + Embed =====
type ChunkEmbedRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SpaceId         string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	ContentSourceId string                 `protobuf:"bytes,2,opt,name=content_source_id,json=contentSourceId,proto3" json:"content_source_id,omitempty"` // FK CONTENT_SOURCE.id (Postgres)
	ContentNodeId   string                 `protobuf:"bytes,3,opt,name=content_node_id,json=contentNodeId,proto3" json:"content_node_id,omitempty"`       // FK ContentNode.id (Neo4j)
	// Types that are valid to be assigned to Source:
	//
	//	*ChunkEmbedRequest_Text
	//	*ChunkEmbedRequest_BlobUrl
	Source        isChunkEmbedRequest_Source `protobuf_oneof:"source"`
	Chunking      *ChunkingConfig            `protobuf:"bytes,20,opt,name=chunking,proto3" json:"chunking,omitempty"`
	Embedding     *EmbeddingConfig           `protobuf:"bytes,21,opt,name=embedding,proto3" json:"embedding,omitempty"`
	BatchSize     int32                      `protobuf:"varint,22,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"` // optional, for future streaming/batching
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkEmbedRequest) Reset() {
	*x = ChunkEmbedRequest{}
	mi := &file_proto_v1_canvas_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkEmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkEmbedRequest) ProtoMessage() {}

func (x *ChunkEmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkEmbedRequest.ProtoReflect.Descriptor instead.
func (*ChunkEmbedRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{7}
}

func (x *ChunkEmbedRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ChunkEmbedRequest) GetContentSourceId() string {
	if x != nil {
		return x.ContentSourceId
	}
	return ""
}

func (x *ChunkEmbedRequest) GetContentNodeId() string {
	if x != nil {
		return x.ContentNodeId
	}
	return ""
}

func (x *ChunkEmbedRequest) GetSource() isChunkEmbedRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ChunkEmbedRequest) GetText() string {
	if x != nil {
		if x, ok := x.Source.(*ChunkEmbedRequest_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ChunkEmbedRequest) GetBlobUrl() string {
	if x != nil {
		if x, ok := x.Source.(*ChunkEmbedRequest_BlobUrl); ok {
			return x.BlobUrl
		}
	}
	return ""
}

func (x *ChunkEmbedRequest) GetChunking() *ChunkingConfig {
	if x != nil {
		return x.Chunking
	}
	return nil
}

func (x *ChunkEmbedRequest) GetEmbedding() *EmbeddingConfig {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *ChunkEmbedRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type isChunkEmbedRequest_Source interface {
	isChunkEmbedRequest_Source()
}

type ChunkEmbedRequest_Text struct {
	Text string `protobuf:"bytes,10,opt,name=text,proto3,oneof"` // inline text
}

type ChunkEmbedRequest_BlobUrl struct {
	BlobUrl string `protobuf:"bytes,11,opt,name=blob_url,json=blobUrl,proto3,oneof"` // URL to fetch processed text (e.g., R2)
}

func (*ChunkEmbedRequest_Text) isChunkEmbedRequest_Source() {}

func (*ChunkEmbedRequest_BlobUrl) isChunkEmbedRequest_Source() {}

type ChunkEmbedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *Chunk                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"` // embedding for the chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkEmbedding) Reset() {
	*x = ChunkEmbedding{}
	mi := &file_proto_v1_canvas_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkEmbedding) ProtoMessage() {}

func (x *ChunkEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkEmbedding.ProtoReflect.Descriptor instead.
func (*ChunkEmbedding) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{8}
}

func (x *ChunkEmbedding) GetChunk() *Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ChunkEmbedding) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type ChunkEmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ChunkEmbedding      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // ordered list aligned with sequence_index
	Dims          int32                  `protobuf:"varint,2,opt,name=dims,proto3" json:"dims,omitempty"`      // embedding dimensionality
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkEmbedResponse) Reset() {
	*x = ChunkEmbedResponse{}
	mi := &file_proto_v1_canvas_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkEmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkEmbedResponse) ProtoMessage() {}

func (x *ChunkEmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkEmbedResponse.ProtoReflect.Descriptor instead.
func (*ChunkEmbedResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{9}
}

func (x *ChunkEmbedResponse) GetResults() []*ChunkEmbedding {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ChunkEmbedResponse) GetDims() int32 {
	if x != nil {
		return x.Dims
	}
	return 0
}

func (x *ChunkEmbedResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ChunkEmbedResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

var File_proto_v1_canvas_proto protoreflect.FileDescriptor

const file_proto_v1_canvas_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/canvas.proto\x12\tcanvas.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xae\x01\n" +
	"\fHealthStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12G\n" +
	"\n" +
	"components\x18\x02 \x03(\v2'.canvas.v1.HealthStatus.ComponentsEntryR\n" +
	"components\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x0eChunkingConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\rtarget_tokens\x18\x02 \x01(\x05R\ftargetTokens\x12'\n" +
	"\x0foverlap_percent\x18\x03 \x01(\x05R\x0eoverlapPercent\x12\x1c\n" +
	"\ttokenizer\x18\x04 \x01(\tR\ttokenizer\">\n" +
	"\x12SpatialCoordinates\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x05R\x01z\"\xdd\x01\n" +
	"\x05Chunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0esequence_index\x18\x02 \x01(\x05R\rsequenceIndex\x12%\n" +
	"\x0estart_position\x18\x03 \x01(\x03R\rstartPosition\x12!\n" +
	"\fend_position\x18\x04 \x01(\x03R\vendPosition\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x129\n" +
	"\blocation\x18\n" +
	" \x01(\v2\x1d.canvas.v1.SpatialCoordinatesR\blocation\"m\n" +
	"\x0fEmbeddingConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\"[\n" +
	"\x11EmbedQueryRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x122\n" +
	"\x06config\x18\n" +
	" \x01(\v2\x1a.canvas.v1.EmbeddingConfigR\x06config\"\x80\x01\n" +
	"\x12EmbedQueryResponse\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\x12\x12\n" +
	"\x04dims\x18\x02 \x01(\x05R\x04dims\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion\"\xcf\x02\n" +
	"\x11ChunkEmbedRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12*\n" +
	"\x11content_source_id\x18\x02 \x01(\tR\x0fcontentSourceId\x12&\n" +
	"\x0fcontent_node_id\x18\x03 \x01(\tR\rcontentNodeId\x12\x14\n" +
	"\x04text\x18\n" +
	" \x01(\tH\x00R\x04text\x12\x1b\n" +
	"\bblob_url\x18\v \x01(\tH\x00R\ablobUrl\x125\n" +
	"\bchunking\x18\x14 \x01(\v2\x19.canvas.v1.ChunkingConfigR\bchunking\x128\n" +
	"\tembedding\x18\x15 \x01(\v2\x1a.canvas.v1.EmbeddingConfigR\tembedding\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x16 \x01(\x05R\tbatchSizeB\b\n" +
	"\x06source\"P\n" +
	"\x0eChunkEmbedding\x12&\n" +
	"\x05chunk\x18\x01 \x01(\v2\x10.canvas.v1.ChunkR\x05chunk\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\"\x9d\x01\n" +
	"\x12ChunkEmbedResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.canvas.v1.ChunkEmbeddingR\aresults\x12\x12\n" +
	"\x04dims\x18\x02 \x01(\x05R\x04dims\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion2\xe2\x01\n" +
	"\x0eCanvasInternal\x12I\n" +
	"\n" +
	"ChunkEmbed\x12\x1c.canvas.v1.ChunkEmbedRequest\x1a\x1d.canvas.v1.ChunkEmbedResponse\x12I\n" +
	"\n" +
	"EmbedQuery\x12\x1c.canvas.v1.EmbedQueryRequest\x1a\x1d.canvas.v1.EmbedQueryResponse\x12:\n" +
	"\aHealthz\x12\x16.google.protobuf.Empty\x1a\x17.canvas.v1.HealthStatusB-Z+demo/ms_canvas/go_app/api/proto/v1;canvasv1b\x06proto3"

var (
	file_proto_v1_canvas_proto_rawDescOnce sync.Once
	file_proto_v1_canvas_proto_rawDescData []byte
)

func file_proto_v1_canvas_proto_rawDescGZIP() []byte {
	file_proto_v1_canvas_proto_rawDescOnce.Do(func() {
		file_proto_v1_canvas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_canvas_proto_rawDesc), len(file_proto_v1_canvas_proto_rawDesc)))
	})
	return file_proto_v1_canvas_proto_rawDescData
}

var file_proto_v1_canvas_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_v1_canvas_proto_goTypes = []any{
	(*HealthStatus)(nil),       // 0: canvas.v1.HealthStatus
	(*ChunkingConfig)(nil),     // 1: canvas.v1.ChunkingConfig
	(*SpatialCoordinates)(nil), // 2: canvas.v1.SpatialCoordinates
	(*Chunk)(nil),              // 3: canvas.v1.Chunk
	(*EmbeddingConfig)(nil),    // 4: canvas.v1.EmbeddingConfig
	(*EmbedQueryRequest)(nil),  // 5: canvas.v1.EmbedQueryRequest
	(*EmbedQueryResponse)(nil), // 6: canvas.v1.EmbedQueryResponse
	(*ChunkEmbedRequest)(nil),  // 7: canvas.v1.ChunkEmbedRequest
	(*ChunkEmbedding)(nil),     // 8: canvas.v1.ChunkEmbedding
	(*ChunkEmbedResponse)(nil), // 9: canvas.v1.ChunkEmbedResponse
	nil,                        // 10: canvas.v1.HealthStatus.ComponentsEntry
	(*emptypb.Empty)(nil),      // 11: google.protobuf.Empty
}
var file_proto_v1_canvas_proto_depIdxs = []int32{
	10, // 0: canvas.v1.HealthStatus.components:type_name -> canvas.v1.HealthStatus.ComponentsEntry
	2,  // 1: canvas.v1.Chunk.location:type_name -> canvas.v1.SpatialCoordinates
	4,  // 2: canvas.v1.EmbedQueryRequest.config:type_name -> canvas.v1.EmbeddingConfig
	1,  // 3: canvas.v1.ChunkEmbedRequest.chunking:type_name -> canvas.v1.ChunkingConfig
	4,  // 4: canvas.v1.ChunkEmbedRequest.embedding:type_name -> canvas.v1.EmbeddingConfig
	3,  // 5: canvas.v1.ChunkEmbedding.chunk:type_name -> canvas.v1.Chunk
	8,  // 6: canvas.v1.ChunkEmbedResponse.results:type_name -> canvas.v1.ChunkEmbedding
	7,  // 7: canvas.v1.CanvasInternal.ChunkEmbed:input_type -> canvas.v1.ChunkEmbedRequest
	5,  // 8: canvas.v1.CanvasInternal.EmbedQuery:input_type -> canvas.v1.EmbedQueryRequest
	11, // 9: canvas.v1.CanvasInternal.Healthz:input_type -> google.protobuf.Empty
	9,  // 10: canvas.v1.CanvasInternal.ChunkEmbed:output_type -> canvas.v1.ChunkEmbedResponse
	6,  // 11: canvas.v1.CanvasInternal.EmbedQuery:output_type -> canvas.v1.EmbedQueryResponse
	0,  // 12: canvas.v1.CanvasInternal.Healthz:output_type -> canvas.v1.HealthStatus
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_v1_canvas_proto_init() }
func file_proto_v1_canvas_proto_init() {
	if File_proto_v1_canvas_proto != nil {
		return
	}
	file_proto_v1_canvas_proto_msgTypes[7].OneofWrappers = []any{
		(*ChunkEmbedRequest_Text)(nil),
		(*ChunkEmbedRequest_BlobUrl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_canvas_proto_rawDesc), len(file_proto_v1_canvas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_canvas_proto_goTypes,
		DependencyIndexes: file_proto_v1_canvas_proto_depIdxs,
		MessageInfos:      file_proto_v1_canvas_proto_msgTypes,
	}.Build()
	File_proto_v1_canvas_proto = out.File
	file_proto_v1_canvas_proto_goTypes = nil
	file_proto_v1_canvas_proto_depIdxs = nil
}
