version: '3.8'

services:
  backend-go:
    build:
      context: ./backend-go
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      # - ML_SERVICE_URL=http://backend-py:5000
      # - QDRANT_HOST=qdrant
      # - QDRANT_PORT=6333
      # - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./data:/app/data
    # depends_on:
    #   - qdrant
    #   - backend-py
    restart: unless-stopped

  backend-py:
    build:
      context: ./backend-py
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend-go
    restart: unless-stopped

volumes:
  qdrant_data: 