// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: proto/v1/canvas.proto

package canvasv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Components    map[string]string      `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_proto_v1_canvas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{0}
}

func (x *HealthStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthStatus) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

// ===== Chunking =====
type ChunkingConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// fixed to "sentence" for this phase
	Type           string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                            // "sentence"
	TargetTokens   int32  `protobuf:"varint,2,opt,name=target_tokens,json=targetTokens,proto3" json:"target_tokens,omitempty"`       // default 300
	OverlapPercent int32  `protobuf:"varint,3,opt,name=overlap_percent,json=overlapPercent,proto3" json:"overlap_percent,omitempty"` // default 10
	Tokenizer      string `protobuf:"bytes,4,opt,name=tokenizer,proto3" json:"tokenizer,omitempty"`                                  // e.g., "tiktoken:cl100k_base"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChunkingConfig) Reset() {
	*x = ChunkingConfig{}
	mi := &file_proto_v1_canvas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkingConfig) ProtoMessage() {}

func (x *ChunkingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkingConfig.ProtoReflect.Descriptor instead.
func (*ChunkingConfig) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{1}
}

func (x *ChunkingConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChunkingConfig) GetTargetTokens() int32 {
	if x != nil {
		return x.TargetTokens
	}
	return 0
}

func (x *ChunkingConfig) GetOverlapPercent() int32 {
	if x != nil {
		return x.OverlapPercent
	}
	return 0
}

func (x *ChunkingConfig) GetTokenizer() string {
	if x != nil {
		return x.Tokenizer
	}
	return ""
}

type ChunkTextRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SpaceId         string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	ContentSourceId string                 `protobuf:"bytes,2,opt,name=content_source_id,json=contentSourceId,proto3" json:"content_source_id,omitempty"` // FK CONTENT_SOURCE.id (Postgres)
	ContentNodeId   string                 `protobuf:"bytes,3,opt,name=content_node_id,json=contentNodeId,proto3" json:"content_node_id,omitempty"`       // FK ContentNode.id (Neo4j)
	// Types that are valid to be assigned to Source:
	//
	//	*ChunkTextRequest_Text
	//	*ChunkTextRequest_BlobUrl
	Source        isChunkTextRequest_Source `protobuf_oneof:"source"`
	Config        *ChunkingConfig           `protobuf:"bytes,20,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkTextRequest) Reset() {
	*x = ChunkTextRequest{}
	mi := &file_proto_v1_canvas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkTextRequest) ProtoMessage() {}

func (x *ChunkTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkTextRequest.ProtoReflect.Descriptor instead.
func (*ChunkTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkTextRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ChunkTextRequest) GetContentSourceId() string {
	if x != nil {
		return x.ContentSourceId
	}
	return ""
}

func (x *ChunkTextRequest) GetContentNodeId() string {
	if x != nil {
		return x.ContentNodeId
	}
	return ""
}

func (x *ChunkTextRequest) GetSource() isChunkTextRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ChunkTextRequest) GetText() string {
	if x != nil {
		if x, ok := x.Source.(*ChunkTextRequest_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *ChunkTextRequest) GetBlobUrl() string {
	if x != nil {
		if x, ok := x.Source.(*ChunkTextRequest_BlobUrl); ok {
			return x.BlobUrl
		}
	}
	return ""
}

func (x *ChunkTextRequest) GetConfig() *ChunkingConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type isChunkTextRequest_Source interface {
	isChunkTextRequest_Source()
}

type ChunkTextRequest_Text struct {
	Text string `protobuf:"bytes,10,opt,name=text,proto3,oneof"` // inline text
}

type ChunkTextRequest_BlobUrl struct {
	BlobUrl string `protobuf:"bytes,11,opt,name=blob_url,json=blobUrl,proto3,oneof"` // URL to fetch processed text (e.g., R2)
}

func (*ChunkTextRequest_Text) isChunkTextRequest_Source() {}

func (*ChunkTextRequest_BlobUrl) isChunkTextRequest_Source() {}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                             // optional client-generated id or empty
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`                                // 0-based ordinal
	StartPosition int64                  `protobuf:"varint,3,opt,name=start_position,json=startPosition,proto3" json:"start_position,omitempty"` // character offset in original content
	EndPosition   int64                  `protobuf:"varint,4,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`       // character offset in original content (exclusive)
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                                   // normalized chunk text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_proto_v1_canvas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{3}
}

func (x *Chunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chunk) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Chunk) GetStartPosition() int64 {
	if x != nil {
		return x.StartPosition
	}
	return 0
}

func (x *Chunk) GetEndPosition() int64 {
	if x != nil {
		return x.EndPosition
	}
	return 0
}

func (x *Chunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChunkTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*Chunk               `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkTextResponse) Reset() {
	*x = ChunkTextResponse{}
	mi := &file_proto_v1_canvas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkTextResponse) ProtoMessage() {}

func (x *ChunkTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkTextResponse.ProtoReflect.Descriptor instead.
func (*ChunkTextResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkTextResponse) GetChunks() []*Chunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

// ===== Embedding =====
type EmbeddingConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // e.g., openai, local
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingConfig) Reset() {
	*x = EmbeddingConfig{}
	mi := &file_proto_v1_canvas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingConfig) ProtoMessage() {}

func (x *EmbeddingConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingConfig.ProtoReflect.Descriptor instead.
func (*EmbeddingConfig) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{5}
}

func (x *EmbeddingConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *EmbeddingConfig) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *EmbeddingConfig) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

type EmbedChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkIds      []string               `protobuf:"bytes,1,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"` // positions or ids corresponding to previously returned chunks
	Contents      []string               `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`                 // optional, can embed by content directly
	Config        *EmbeddingConfig       `protobuf:"bytes,10,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedChunksRequest) Reset() {
	*x = EmbedChunksRequest{}
	mi := &file_proto_v1_canvas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedChunksRequest) ProtoMessage() {}

func (x *EmbedChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedChunksRequest.ProtoReflect.Descriptor instead.
func (*EmbedChunksRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{6}
}

func (x *EmbedChunksRequest) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

func (x *EmbedChunksRequest) GetContents() []string {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *EmbedChunksRequest) GetConfig() *EmbeddingConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type EmbedChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlatVectors   []float32              `protobuf:"fixed32,1,rep,packed,name=flat_vectors,json=flatVectors,proto3" json:"flat_vectors,omitempty"` // concatenated floats; use dims to reshape
	Dims          int32                  `protobuf:"varint,2,opt,name=dims,proto3" json:"dims,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedChunksResponse) Reset() {
	*x = EmbedChunksResponse{}
	mi := &file_proto_v1_canvas_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedChunksResponse) ProtoMessage() {}

func (x *EmbedChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedChunksResponse.ProtoReflect.Descriptor instead.
func (*EmbedChunksResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{7}
}

func (x *EmbedChunksResponse) GetFlatVectors() []float32 {
	if x != nil {
		return x.FlatVectors
	}
	return nil
}

func (x *EmbedChunksResponse) GetDims() int32 {
	if x != nil {
		return x.Dims
	}
	return 0
}

func (x *EmbedChunksResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *EmbedChunksResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

type EmbedQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Config        *EmbeddingConfig       `protobuf:"bytes,10,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedQueryRequest) Reset() {
	*x = EmbedQueryRequest{}
	mi := &file_proto_v1_canvas_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedQueryRequest) ProtoMessage() {}

func (x *EmbedQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedQueryRequest.ProtoReflect.Descriptor instead.
func (*EmbedQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{8}
}

func (x *EmbedQueryRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EmbedQueryRequest) GetConfig() *EmbeddingConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type EmbedQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Dims          int32                  `protobuf:"varint,2,opt,name=dims,proto3" json:"dims,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,4,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedQueryResponse) Reset() {
	*x = EmbedQueryResponse{}
	mi := &file_proto_v1_canvas_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedQueryResponse) ProtoMessage() {}

func (x *EmbedQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_canvas_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedQueryResponse.ProtoReflect.Descriptor instead.
func (*EmbedQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_canvas_proto_rawDescGZIP(), []int{9}
}

func (x *EmbedQueryResponse) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *EmbedQueryResponse) GetDims() int32 {
	if x != nil {
		return x.Dims
	}
	return 0
}

func (x *EmbedQueryResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *EmbedQueryResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

var File_proto_v1_canvas_proto protoreflect.FileDescriptor

const file_proto_v1_canvas_proto_rawDesc = "" +
	"\n" +
	"\x15proto/v1/canvas.proto\x12\tcanvas.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xae\x01\n" +
	"\fHealthStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12G\n" +
	"\n" +
	"components\x18\x02 \x03(\v2'.canvas.v1.HealthStatus.ComponentsEntryR\n" +
	"components\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\x0eChunkingConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\rtarget_tokens\x18\x02 \x01(\x05R\ftargetTokens\x12'\n" +
	"\x0foverlap_percent\x18\x03 \x01(\x05R\x0eoverlapPercent\x12\x1c\n" +
	"\ttokenizer\x18\x04 \x01(\tR\ttokenizer\"\xf1\x01\n" +
	"\x10ChunkTextRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12*\n" +
	"\x11content_source_id\x18\x02 \x01(\tR\x0fcontentSourceId\x12&\n" +
	"\x0fcontent_node_id\x18\x03 \x01(\tR\rcontentNodeId\x12\x14\n" +
	"\x04text\x18\n" +
	" \x01(\tH\x00R\x04text\x12\x1b\n" +
	"\bblob_url\x18\v \x01(\tH\x00R\ablobUrl\x121\n" +
	"\x06config\x18\x14 \x01(\v2\x19.canvas.v1.ChunkingConfigR\x06configB\b\n" +
	"\x06source\"\x97\x01\n" +
	"\x05Chunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12%\n" +
	"\x0estart_position\x18\x03 \x01(\x03R\rstartPosition\x12!\n" +
	"\fend_position\x18\x04 \x01(\x03R\vendPosition\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\"=\n" +
	"\x11ChunkTextResponse\x12(\n" +
	"\x06chunks\x18\x01 \x03(\v2\x10.canvas.v1.ChunkR\x06chunks\"m\n" +
	"\x0fEmbeddingConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\"\x81\x01\n" +
	"\x12EmbedChunksRequest\x12\x1b\n" +
	"\tchunk_ids\x18\x01 \x03(\tR\bchunkIds\x12\x1a\n" +
	"\bcontents\x18\x02 \x03(\tR\bcontents\x122\n" +
	"\x06config\x18\n" +
	" \x01(\v2\x1a.canvas.v1.EmbeddingConfigR\x06config\"\x8c\x01\n" +
	"\x13EmbedChunksResponse\x12!\n" +
	"\fflat_vectors\x18\x01 \x03(\x02R\vflatVectors\x12\x12\n" +
	"\x04dims\x18\x02 \x01(\x05R\x04dims\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion\"[\n" +
	"\x11EmbedQueryRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x122\n" +
	"\x06config\x18\n" +
	" \x01(\v2\x1a.canvas.v1.EmbeddingConfigR\x06config\"\x80\x01\n" +
	"\x12EmbedQueryResponse\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\x12\x12\n" +
	"\x04dims\x18\x02 \x01(\x05R\x04dims\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12#\n" +
	"\rmodel_version\x18\x04 \x01(\tR\fmodelVersion2\xad\x02\n" +
	"\x0eCanvasInternal\x12F\n" +
	"\tChunkText\x12\x1b.canvas.v1.ChunkTextRequest\x1a\x1c.canvas.v1.ChunkTextResponse\x12L\n" +
	"\vEmbedChunks\x12\x1d.canvas.v1.EmbedChunksRequest\x1a\x1e.canvas.v1.EmbedChunksResponse\x12I\n" +
	"\n" +
	"EmbedQuery\x12\x1c.canvas.v1.EmbedQueryRequest\x1a\x1d.canvas.v1.EmbedQueryResponse\x12:\n" +
	"\aHealthz\x12\x16.google.protobuf.Empty\x1a\x17.canvas.v1.HealthStatusB\"Z demo/ms_canvas/proto/v1;canvasv1b\x06proto3"

var (
	file_proto_v1_canvas_proto_rawDescOnce sync.Once
	file_proto_v1_canvas_proto_rawDescData []byte
)

func file_proto_v1_canvas_proto_rawDescGZIP() []byte {
	file_proto_v1_canvas_proto_rawDescOnce.Do(func() {
		file_proto_v1_canvas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_canvas_proto_rawDesc), len(file_proto_v1_canvas_proto_rawDesc)))
	})
	return file_proto_v1_canvas_proto_rawDescData
}

var file_proto_v1_canvas_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_v1_canvas_proto_goTypes = []any{
	(*HealthStatus)(nil),        // 0: canvas.v1.HealthStatus
	(*ChunkingConfig)(nil),      // 1: canvas.v1.ChunkingConfig
	(*ChunkTextRequest)(nil),    // 2: canvas.v1.ChunkTextRequest
	(*Chunk)(nil),               // 3: canvas.v1.Chunk
	(*ChunkTextResponse)(nil),   // 4: canvas.v1.ChunkTextResponse
	(*EmbeddingConfig)(nil),     // 5: canvas.v1.EmbeddingConfig
	(*EmbedChunksRequest)(nil),  // 6: canvas.v1.EmbedChunksRequest
	(*EmbedChunksResponse)(nil), // 7: canvas.v1.EmbedChunksResponse
	(*EmbedQueryRequest)(nil),   // 8: canvas.v1.EmbedQueryRequest
	(*EmbedQueryResponse)(nil),  // 9: canvas.v1.EmbedQueryResponse
	nil,                         // 10: canvas.v1.HealthStatus.ComponentsEntry
	(*emptypb.Empty)(nil),       // 11: google.protobuf.Empty
}
var file_proto_v1_canvas_proto_depIdxs = []int32{
	10, // 0: canvas.v1.HealthStatus.components:type_name -> canvas.v1.HealthStatus.ComponentsEntry
	1,  // 1: canvas.v1.ChunkTextRequest.config:type_name -> canvas.v1.ChunkingConfig
	3,  // 2: canvas.v1.ChunkTextResponse.chunks:type_name -> canvas.v1.Chunk
	5,  // 3: canvas.v1.EmbedChunksRequest.config:type_name -> canvas.v1.EmbeddingConfig
	5,  // 4: canvas.v1.EmbedQueryRequest.config:type_name -> canvas.v1.EmbeddingConfig
	2,  // 5: canvas.v1.CanvasInternal.ChunkText:input_type -> canvas.v1.ChunkTextRequest
	6,  // 6: canvas.v1.CanvasInternal.EmbedChunks:input_type -> canvas.v1.EmbedChunksRequest
	8,  // 7: canvas.v1.CanvasInternal.EmbedQuery:input_type -> canvas.v1.EmbedQueryRequest
	11, // 8: canvas.v1.CanvasInternal.Healthz:input_type -> google.protobuf.Empty
	4,  // 9: canvas.v1.CanvasInternal.ChunkText:output_type -> canvas.v1.ChunkTextResponse
	7,  // 10: canvas.v1.CanvasInternal.EmbedChunks:output_type -> canvas.v1.EmbedChunksResponse
	9,  // 11: canvas.v1.CanvasInternal.EmbedQuery:output_type -> canvas.v1.EmbedQueryResponse
	0,  // 12: canvas.v1.CanvasInternal.Healthz:output_type -> canvas.v1.HealthStatus
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_v1_canvas_proto_init() }
func file_proto_v1_canvas_proto_init() {
	if File_proto_v1_canvas_proto != nil {
		return
	}
	file_proto_v1_canvas_proto_msgTypes[2].OneofWrappers = []any{
		(*ChunkTextRequest_Text)(nil),
		(*ChunkTextRequest_BlobUrl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_canvas_proto_rawDesc), len(file_proto_v1_canvas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_canvas_proto_goTypes,
		DependencyIndexes: file_proto_v1_canvas_proto_depIdxs,
		MessageInfos:      file_proto_v1_canvas_proto_msgTypes,
	}.Build()
	File_proto_v1_canvas_proto = out.File
	file_proto_v1_canvas_proto_goTypes = nil
	file_proto_v1_canvas_proto_depIdxs = nil
}
