// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: api/proto/v1/knowledge.proto

package knowledgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type ContentStatus int32

const (
	ContentStatus_CONTENT_STATUS_UNSPECIFIED ContentStatus = 0
	ContentStatus_UPLOADING                  ContentStatus = 1
	ContentStatus_UPLOADED                   ContentStatus = 2
	ContentStatus_PROCESSING                 ContentStatus = 3
	ContentStatus_PROCESSED                  ContentStatus = 4
	ContentStatus_FAILED                     ContentStatus = 5
)

// Enum value maps for ContentStatus.
var (
	ContentStatus_name = map[int32]string{
		0: "CONTENT_STATUS_UNSPECIFIED",
		1: "UPLOADING",
		2: "UPLOADED",
		3: "PROCESSING",
		4: "PROCESSED",
		5: "FAILED",
	}
	ContentStatus_value = map[string]int32{
		"CONTENT_STATUS_UNSPECIFIED": 0,
		"UPLOADING":                  1,
		"UPLOADED":                   2,
		"PROCESSING":                 3,
		"PROCESSED":                  4,
		"FAILED":                     5,
	}
)

func (x ContentStatus) Enum() *ContentStatus {
	p := new(ContentStatus)
	*p = x
	return p
}

func (x ContentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_knowledge_proto_enumTypes[0].Descriptor()
}

func (ContentStatus) Type() protoreflect.EnumType {
	return &file_api_proto_v1_knowledge_proto_enumTypes[0]
}

func (x ContentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentStatus.Descriptor instead.
func (ContentStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

type RelationType int32

const (
	RelationType_RELATION_TYPE_UNSPECIFIED RelationType = 0
	RelationType_REFERENCES                RelationType = 1
	RelationType_CONTAINS                  RelationType = 2
	RelationType_RELATED                   RelationType = 3
	RelationType_FOLLOWS                   RelationType = 4
)

// Enum value maps for RelationType.
var (
	RelationType_name = map[int32]string{
		0: "RELATION_TYPE_UNSPECIFIED",
		1: "REFERENCES",
		2: "CONTAINS",
		3: "RELATED",
		4: "FOLLOWS",
	}
	RelationType_value = map[string]int32{
		"RELATION_TYPE_UNSPECIFIED": 0,
		"REFERENCES":                1,
		"CONTAINS":                  2,
		"RELATED":                   3,
		"FOLLOWS":                   4,
	}
)

func (x RelationType) Enum() *RelationType {
	p := new(RelationType)
	*p = x
	return p
}

func (x RelationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_knowledge_proto_enumTypes[1].Descriptor()
}

func (RelationType) Type() protoreflect.EnumType {
	return &file_api_proto_v1_knowledge_proto_enumTypes[1]
}

func (x RelationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationType.Descriptor instead.
func (RelationType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

type LinkDirection int32

const (
	LinkDirection_LINK_DIRECTION_UNSPECIFIED LinkDirection = 0
	LinkDirection_INBOUND                    LinkDirection = 1
	LinkDirection_OUTBOUND                   LinkDirection = 2
	LinkDirection_BOTH                       LinkDirection = 3
)

// Enum value maps for LinkDirection.
var (
	LinkDirection_name = map[int32]string{
		0: "LINK_DIRECTION_UNSPECIFIED",
		1: "INBOUND",
		2: "OUTBOUND",
		3: "BOTH",
	}
	LinkDirection_value = map[string]int32{
		"LINK_DIRECTION_UNSPECIFIED": 0,
		"INBOUND":                    1,
		"OUTBOUND":                   2,
		"BOTH":                       3,
	}
)

func (x LinkDirection) Enum() *LinkDirection {
	p := new(LinkDirection)
	*p = x
	return p
}

func (x LinkDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_knowledge_proto_enumTypes[2].Descriptor()
}

func (LinkDirection) Type() protoreflect.EnumType {
	return &file_api_proto_v1_knowledge_proto_enumTypes[2]
}

func (x LinkDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkDirection.Descriptor instead.
func (LinkDirection) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

// Specifies which object (original or processed) an operation targets
type DownloadObjectKind int32

const (
	DownloadObjectKind_DOWNLOAD_OBJECT_KIND_UNSPECIFIED DownloadObjectKind = 0
	DownloadObjectKind_DOWNLOAD_OBJECT_KIND_ORIGINAL    DownloadObjectKind = 1 // source/original object
	DownloadObjectKind_DOWNLOAD_OBJECT_KIND_PROCESSED   DownloadObjectKind = 2 // processed object
)

// Enum value maps for DownloadObjectKind.
var (
	DownloadObjectKind_name = map[int32]string{
		0: "DOWNLOAD_OBJECT_KIND_UNSPECIFIED",
		1: "DOWNLOAD_OBJECT_KIND_ORIGINAL",
		2: "DOWNLOAD_OBJECT_KIND_PROCESSED",
	}
	DownloadObjectKind_value = map[string]int32{
		"DOWNLOAD_OBJECT_KIND_UNSPECIFIED": 0,
		"DOWNLOAD_OBJECT_KIND_ORIGINAL":    1,
		"DOWNLOAD_OBJECT_KIND_PROCESSED":   2,
	}
)

func (x DownloadObjectKind) Enum() *DownloadObjectKind {
	p := new(DownloadObjectKind)
	*p = x
	return p
}

func (x DownloadObjectKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DownloadObjectKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_v1_knowledge_proto_enumTypes[3].Descriptor()
}

func (DownloadObjectKind) Type() protoreflect.EnumType {
	return &file_api_proto_v1_knowledge_proto_enumTypes[3]
}

func (x DownloadObjectKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DownloadObjectKind.Descriptor instead.
func (DownloadObjectKind) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

// Common Messages
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// Core Entities
type SpaceStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContentCount   int64                  `protobuf:"varint,1,opt,name=content_count,json=contentCount,proto3" json:"content_count,omitempty"`
	LinkCount      int64                  `protobuf:"varint,2,opt,name=link_count,json=linkCount,proto3" json:"link_count,omitempty"`
	LastActivityAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_activity_at,json=lastActivityAt,proto3" json:"last_activity_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpaceStats) Reset() {
	*x = SpaceStats{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceStats) ProtoMessage() {}

func (x *SpaceStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceStats.ProtoReflect.Descriptor instead.
func (*SpaceStats) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *SpaceStats) GetContentCount() int64 {
	if x != nil {
		return x.ContentCount
	}
	return 0
}

func (x *SpaceStats) GetLinkCount() int64 {
	if x != nil {
		return x.LinkCount
	}
	return 0
}

func (x *SpaceStats) GetLastActivityAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivityAt
	}
	return nil
}

type Space struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Stats         *SpaceStats            `protobuf:"bytes,10,opt,name=stats,proto3" json:"stats,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Space) Reset() {
	*x = Space{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Space) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Space) ProtoMessage() {}

func (x *Space) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Space.ProtoReflect.Descriptor instead.
func (*Space) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *Space) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Space) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Space) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Space) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Space) GetStats() *SpaceStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Space) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Space) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ContentSource struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SpaceId           string                 `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Status            ContentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=knowledge.v1.ContentStatus" json:"status,omitempty"`
	OwnerId           string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Source            string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	MimeType          string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes         int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Title             string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	OriginalBlobHash  string                 `protobuf:"bytes,9,opt,name=original_blob_hash,json=originalBlobHash,proto3" json:"original_blob_hash,omitempty"`
	ProcessedBlobHash string                 `protobuf:"bytes,10,opt,name=processed_blob_hash,json=processedBlobHash,proto3" json:"processed_blob_hash,omitempty"`
	ContentSummary    string                 `protobuf:"bytes,11,opt,name=content_summary,json=contentSummary,proto3" json:"content_summary,omitempty"`
	Keywords          []string               `protobuf:"bytes,12,rep,name=keywords,proto3" json:"keywords,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContentSource) Reset() {
	*x = ContentSource{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentSource) ProtoMessage() {}

func (x *ContentSource) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentSource.ProtoReflect.Descriptor instead.
func (*ContentSource) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *ContentSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContentSource) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ContentSource) GetStatus() ContentStatus {
	if x != nil {
		return x.Status
	}
	return ContentStatus_CONTENT_STATUS_UNSPECIFIED
}

func (x *ContentSource) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ContentSource) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ContentSource) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ContentSource) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ContentSource) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContentSource) GetOriginalBlobHash() string {
	if x != nil {
		return x.OriginalBlobHash
	}
	return ""
}

func (x *ContentSource) GetProcessedBlobHash() string {
	if x != nil {
		return x.ProcessedBlobHash
	}
	return ""
}

func (x *ContentSource) GetContentSummary() string {
	if x != nil {
		return x.ContentSummary
	}
	return ""
}

func (x *ContentSource) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *ContentSource) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ContentSource) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Simple link (used for bulk list)
type KnowledgeLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromContentId string                 `protobuf:"bytes,2,opt,name=from_content_id,json=fromContentId,proto3" json:"from_content_id,omitempty"`
	ToContentId   string                 `protobuf:"bytes,3,opt,name=to_content_id,json=toContentId,proto3" json:"to_content_id,omitempty"`
	RelationType  RelationType           `protobuf:"varint,4,opt,name=relation_type,json=relationType,proto3,enum=knowledge.v1.RelationType" json:"relation_type,omitempty"`
	Weight        float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeLink) Reset() {
	*x = KnowledgeLink{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeLink) ProtoMessage() {}

func (x *KnowledgeLink) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeLink.ProtoReflect.Descriptor instead.
func (*KnowledgeLink) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *KnowledgeLink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeLink) GetFromContentId() string {
	if x != nil {
		return x.FromContentId
	}
	return ""
}

func (x *KnowledgeLink) GetToContentId() string {
	if x != nil {
		return x.ToContentId
	}
	return ""
}

func (x *KnowledgeLink) GetRelationType() RelationType {
	if x != nil {
		return x.RelationType
	}
	return RelationType_RELATION_TYPE_UNSPECIFIED
}

func (x *KnowledgeLink) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *KnowledgeLink) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KnowledgeLink) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Enriched link view (used for focused list and single get)
type ContentPreview struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ContentSummary string                 `protobuf:"bytes,3,opt,name=content_summary,json=contentSummary,proto3" json:"content_summary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContentPreview) Reset() {
	*x = ContentPreview{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentPreview) ProtoMessage() {}

func (x *ContentPreview) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentPreview.ProtoReflect.Descriptor instead.
func (*ContentPreview) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *ContentPreview) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContentPreview) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ContentPreview) GetContentSummary() string {
	if x != nil {
		return x.ContentSummary
	}
	return ""
}

type EnrichedKnowledgeLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From          *ContentPreview        `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *ContentPreview        `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	RelationType  RelationType           `protobuf:"varint,4,opt,name=relation_type,json=relationType,proto3,enum=knowledge.v1.RelationType" json:"relation_type,omitempty"`
	Weight        float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,98,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,99,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrichedKnowledgeLink) Reset() {
	*x = EnrichedKnowledgeLink{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrichedKnowledgeLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrichedKnowledgeLink) ProtoMessage() {}

func (x *EnrichedKnowledgeLink) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrichedKnowledgeLink.ProtoReflect.Descriptor instead.
func (*EnrichedKnowledgeLink) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *EnrichedKnowledgeLink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EnrichedKnowledgeLink) GetFrom() *ContentPreview {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EnrichedKnowledgeLink) GetTo() *ContentPreview {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EnrichedKnowledgeLink) GetRelationType() RelationType {
	if x != nil {
		return x.RelationType
	}
	return RelationType_RELATION_TYPE_UNSPECIFIED
}

func (x *EnrichedKnowledgeLink) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *EnrichedKnowledgeLink) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *EnrichedKnowledgeLink) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Space Request/Response Messages
type CreateSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpaceRequest) Reset() {
	*x = CreateSpaceRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpaceRequest) ProtoMessage() {}

func (x *CreateSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpaceRequest.ProtoReflect.Descriptor instead.
func (*CreateSpaceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *CreateSpaceRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSpaceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpaceRequest) Reset() {
	*x = GetSpaceRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpaceRequest) ProtoMessage() {}

func (x *GetSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpaceRequest.ProtoReflect.Descriptor instead.
func (*GetSpaceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{8}
}

func (x *GetSpaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSpacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Keywords      []string               `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	AccessLevel   string                 `protobuf:"bytes,4,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAfter  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_after,json=createdAfter,proto3" json:"created_after,omitempty"`
	CreatedBefore *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_before,json=createdBefore,proto3" json:"created_before,omitempty"`
	UpdatedAfter  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_after,json=updatedAfter,proto3" json:"updated_after,omitempty"`
	UpdatedBefore *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_before,json=updatedBefore,proto3" json:"updated_before,omitempty"`
	Page          *Pagination            `protobuf:"bytes,10,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpacesRequest) Reset() {
	*x = ListSpacesRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpacesRequest) ProtoMessage() {}

func (x *ListSpacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpacesRequest.ProtoReflect.Descriptor instead.
func (*ListSpacesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *ListSpacesRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ListSpacesRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListSpacesRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *ListSpacesRequest) GetAccessLevel() string {
	if x != nil {
		return x.AccessLevel
	}
	return ""
}

func (x *ListSpacesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListSpacesRequest) GetCreatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAfter
	}
	return nil
}

func (x *ListSpacesRequest) GetCreatedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedBefore
	}
	return nil
}

func (x *ListSpacesRequest) GetUpdatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAfter
	}
	return nil
}

func (x *ListSpacesRequest) GetUpdatedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedBefore
	}
	return nil
}

func (x *ListSpacesRequest) GetPage() *Pagination {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListSpacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Space               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpacesResponse) Reset() {
	*x = ListSpacesResponse{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpacesResponse) ProtoMessage() {}

func (x *ListSpacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpacesResponse.ProtoReflect.Descriptor instead.
func (*ListSpacesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *ListSpacesResponse) GetItems() []*Space {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListSpacesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Space         *Space                 `protobuf:"bytes,2,opt,name=space,proto3" json:"space,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSpaceRequest) Reset() {
	*x = UpdateSpaceRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpaceRequest) ProtoMessage() {}

func (x *UpdateSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateSpaceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateSpaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSpaceRequest) GetSpace() *Space {
	if x != nil {
		return x.Space
	}
	return nil
}

func (x *UpdateSpaceRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HardDelete    bool                   `protobuf:"varint,2,opt,name=hard_delete,json=hardDelete,proto3" json:"hard_delete,omitempty"`
	Force         bool                   `protobuf:"varint,3,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSpaceRequest) Reset() {
	*x = DeleteSpaceRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSpaceRequest) ProtoMessage() {}

func (x *DeleteSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSpaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteSpaceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteSpaceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteSpaceRequest) GetHardDelete() bool {
	if x != nil {
		return x.HardDelete
	}
	return false
}

func (x *DeleteSpaceRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// Content Source Request/Response Messages
type CreateUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	ObjectKind    DownloadObjectKind     `protobuf:"varint,6,opt,name=object_kind,json=objectKind,proto3,enum=knowledge.v1.DownloadObjectKind" json:"object_kind,omitempty"` // ORIGINAL or PROCESSED (required)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadURLRequest) Reset() {
	*x = CreateUploadURLRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadURLRequest) ProtoMessage() {}

func (x *CreateUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadURLRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{13}
}

func (x *CreateUploadURLRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *CreateUploadURLRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CreateUploadURLRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *CreateUploadURLRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateUploadURLRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateUploadURLRequest) GetObjectKind() DownloadObjectKind {
	if x != nil {
		return x.ObjectKind
	}
	return DownloadObjectKind_DOWNLOAD_OBJECT_KIND_UNSPECIFIED
}

type CreateUploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ContentSource *ContentSource         `protobuf:"bytes,10,opt,name=content_source,json=contentSource,proto3" json:"content_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadURLResponse) Reset() {
	*x = CreateUploadURLResponse{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadURLResponse) ProtoMessage() {}

func (x *CreateUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadURLResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{14}
}

func (x *CreateUploadURLResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *CreateUploadURLResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *CreateUploadURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreateUploadURLResponse) GetContentSource() *ContentSource {
	if x != nil {
		return x.ContentSource
	}
	return nil
}

type ConfirmUploadRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentSourceId string                 `protobuf:"bytes,1,opt,name=content_source_id,json=contentSourceId,proto3" json:"content_source_id,omitempty"`                      // required
	ObjectKind      DownloadObjectKind     `protobuf:"varint,2,opt,name=object_kind,json=objectKind,proto3,enum=knowledge.v1.DownloadObjectKind" json:"object_kind,omitempty"` // required
	BlobHash        string                 `protobuf:"bytes,3,opt,name=blob_hash,json=blobHash,proto3" json:"blob_hash,omitempty"`                                             // required
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfirmUploadRequest) Reset() {
	*x = ConfirmUploadRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmUploadRequest) ProtoMessage() {}

func (x *ConfirmUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmUploadRequest.ProtoReflect.Descriptor instead.
func (*ConfirmUploadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{15}
}

func (x *ConfirmUploadRequest) GetContentSourceId() string {
	if x != nil {
		return x.ContentSourceId
	}
	return ""
}

func (x *ConfirmUploadRequest) GetObjectKind() DownloadObjectKind {
	if x != nil {
		return x.ObjectKind
	}
	return DownloadObjectKind_DOWNLOAD_OBJECT_KIND_UNSPECIFIED
}

func (x *ConfirmUploadRequest) GetBlobHash() string {
	if x != nil {
		return x.BlobHash
	}
	return ""
}

type GetContentSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentSourceRequest) Reset() {
	*x = GetContentSourceRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentSourceRequest) ProtoMessage() {}

func (x *GetContentSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentSourceRequest.ProtoReflect.Descriptor instead.
func (*GetContentSourceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{16}
}

func (x *GetContentSourceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListContentSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Status        ContentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=knowledge.v1.ContentStatus" json:"status,omitempty"`
	Page          *Pagination            `protobuf:"bytes,10,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentSourcesRequest) Reset() {
	*x = ListContentSourcesRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentSourcesRequest) ProtoMessage() {}

func (x *ListContentSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListContentSourcesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{17}
}

func (x *ListContentSourcesRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ListContentSourcesRequest) GetStatus() ContentStatus {
	if x != nil {
		return x.Status
	}
	return ContentStatus_CONTENT_STATUS_UNSPECIFIED
}

func (x *ListContentSourcesRequest) GetPage() *Pagination {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListContentSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ContentSource       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContentSourcesResponse) Reset() {
	*x = ListContentSourcesResponse{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContentSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContentSourcesResponse) ProtoMessage() {}

func (x *ListContentSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContentSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListContentSourcesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{18}
}

func (x *ListContentSourcesResponse) GetItems() []*ContentSource {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListContentSourcesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateContentSourceStatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status            ContentStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=knowledge.v1.ContentStatus" json:"status,omitempty"`
	ProcessedBlobHash string                 `protobuf:"bytes,3,opt,name=processed_blob_hash,json=processedBlobHash,proto3" json:"processed_blob_hash,omitempty"`
	ErrorMessage      string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateContentSourceStatusRequest) Reset() {
	*x = UpdateContentSourceStatusRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContentSourceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContentSourceStatusRequest) ProtoMessage() {}

func (x *UpdateContentSourceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContentSourceStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateContentSourceStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateContentSourceStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateContentSourceStatusRequest) GetStatus() ContentStatus {
	if x != nil {
		return x.Status
	}
	return ContentStatus_CONTENT_STATUS_UNSPECIFIED
}

func (x *UpdateContentSourceStatusRequest) GetProcessedBlobHash() string {
	if x != nil {
		return x.ProcessedBlobHash
	}
	return ""
}

func (x *UpdateContentSourceStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Download URL generation
type GenerateDownloadURLRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContentSourceId string                 `protobuf:"bytes,1,opt,name=content_source_id,json=contentSourceId,proto3" json:"content_source_id,omitempty"`                      // required
	ExpiresSeconds  int32                  `protobuf:"varint,2,opt,name=expires_seconds,json=expiresSeconds,proto3" json:"expires_seconds,omitempty"`                          // optional, server applies bounds and defaults
	ObjectKind      DownloadObjectKind     `protobuf:"varint,3,opt,name=object_kind,json=objectKind,proto3,enum=knowledge.v1.DownloadObjectKind" json:"object_kind,omitempty"` // required
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateDownloadURLRequest) Reset() {
	*x = GenerateDownloadURLRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDownloadURLRequest) ProtoMessage() {}

func (x *GenerateDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GenerateDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{20}
}

func (x *GenerateDownloadURLRequest) GetContentSourceId() string {
	if x != nil {
		return x.ContentSourceId
	}
	return ""
}

func (x *GenerateDownloadURLRequest) GetExpiresSeconds() int32 {
	if x != nil {
		return x.ExpiresSeconds
	}
	return 0
}

func (x *GenerateDownloadURLRequest) GetObjectKind() DownloadObjectKind {
	if x != nil {
		return x.ObjectKind
	}
	return DownloadObjectKind_DOWNLOAD_OBJECT_KIND_UNSPECIFIED
}

type GenerateDownloadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,3,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDownloadURLResponse) Reset() {
	*x = GenerateDownloadURLResponse{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDownloadURLResponse) ProtoMessage() {}

func (x *GenerateDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*GenerateDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{21}
}

func (x *GenerateDownloadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GenerateDownloadURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GenerateDownloadURLResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

// Knowledge Link Request/Response Messages
type CreateKnowledgeLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromContentId string                 `protobuf:"bytes,1,opt,name=from_content_id,json=fromContentId,proto3" json:"from_content_id,omitempty"`
	ToContentId   string                 `protobuf:"bytes,2,opt,name=to_content_id,json=toContentId,proto3" json:"to_content_id,omitempty"`
	RelationType  RelationType           `protobuf:"varint,3,opt,name=relation_type,json=relationType,proto3,enum=knowledge.v1.RelationType" json:"relation_type,omitempty"`
	Weight        float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKnowledgeLinkRequest) Reset() {
	*x = CreateKnowledgeLinkRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeLinkRequest) ProtoMessage() {}

func (x *CreateKnowledgeLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{22}
}

func (x *CreateKnowledgeLinkRequest) GetFromContentId() string {
	if x != nil {
		return x.FromContentId
	}
	return ""
}

func (x *CreateKnowledgeLinkRequest) GetToContentId() string {
	if x != nil {
		return x.ToContentId
	}
	return ""
}

func (x *CreateKnowledgeLinkRequest) GetRelationType() RelationType {
	if x != nil {
		return x.RelationType
	}
	return RelationType_RELATION_TYPE_UNSPECIFIED
}

func (x *CreateKnowledgeLinkRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type GetKnowledgeLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeLinkRequest) Reset() {
	*x = GetKnowledgeLinkRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeLinkRequest) ProtoMessage() {}

func (x *GetKnowledgeLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeLinkRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgeLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{23}
}

func (x *GetKnowledgeLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Focused, enriched list by content
type ListKnowledgeLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Direction     LinkDirection          `protobuf:"varint,2,opt,name=direction,proto3,enum=knowledge.v1.LinkDirection" json:"direction,omitempty"`
	RelationType  RelationType           `protobuf:"varint,3,opt,name=relation_type,json=relationType,proto3,enum=knowledge.v1.RelationType" json:"relation_type,omitempty"`
	Page          *Pagination            `protobuf:"bytes,10,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnowledgeLinksRequest) Reset() {
	*x = ListKnowledgeLinksRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgeLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeLinksRequest) ProtoMessage() {}

func (x *ListKnowledgeLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeLinksRequest.ProtoReflect.Descriptor instead.
func (*ListKnowledgeLinksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{24}
}

func (x *ListKnowledgeLinksRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *ListKnowledgeLinksRequest) GetDirection() LinkDirection {
	if x != nil {
		return x.Direction
	}
	return LinkDirection_LINK_DIRECTION_UNSPECIFIED
}

func (x *ListKnowledgeLinksRequest) GetRelationType() RelationType {
	if x != nil {
		return x.RelationType
	}
	return RelationType_RELATION_TYPE_UNSPECIFIED
}

func (x *ListKnowledgeLinksRequest) GetPage() *Pagination {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListKnowledgeLinksResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*EnrichedKnowledgeLink `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnowledgeLinksResponse) Reset() {
	*x = ListKnowledgeLinksResponse{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgeLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeLinksResponse) ProtoMessage() {}

func (x *ListKnowledgeLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeLinksResponse.ProtoReflect.Descriptor instead.
func (*ListKnowledgeLinksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{25}
}

func (x *ListKnowledgeLinksResponse) GetItems() []*EnrichedKnowledgeLink {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListKnowledgeLinksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Bulk, simple list by space
type ListAllSpaceLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpaceId       string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	RelationType  RelationType           `protobuf:"varint,2,opt,name=relation_type,json=relationType,proto3,enum=knowledge.v1.RelationType" json:"relation_type,omitempty"`
	Page          *Pagination            `protobuf:"bytes,10,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllSpaceLinksRequest) Reset() {
	*x = ListAllSpaceLinksRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllSpaceLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllSpaceLinksRequest) ProtoMessage() {}

func (x *ListAllSpaceLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllSpaceLinksRequest.ProtoReflect.Descriptor instead.
func (*ListAllSpaceLinksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{26}
}

func (x *ListAllSpaceLinksRequest) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ListAllSpaceLinksRequest) GetRelationType() RelationType {
	if x != nil {
		return x.RelationType
	}
	return RelationType_RELATION_TYPE_UNSPECIFIED
}

func (x *ListAllSpaceLinksRequest) GetPage() *Pagination {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListAllSpaceLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KnowledgeLink       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllSpaceLinksResponse) Reset() {
	*x = ListAllSpaceLinksResponse{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllSpaceLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllSpaceLinksResponse) ProtoMessage() {}

func (x *ListAllSpaceLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllSpaceLinksResponse.ProtoReflect.Descriptor instead.
func (*ListAllSpaceLinksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{27}
}

func (x *ListAllSpaceLinksResponse) GetItems() []*KnowledgeLink {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAllSpaceLinksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateKnowledgeLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Link          *KnowledgeLink         `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKnowledgeLinkRequest) Reset() {
	*x = UpdateKnowledgeLinkRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKnowledgeLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKnowledgeLinkRequest) ProtoMessage() {}

func (x *UpdateKnowledgeLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKnowledgeLinkRequest.ProtoReflect.Descriptor instead.
func (*UpdateKnowledgeLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateKnowledgeLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateKnowledgeLinkRequest) GetLink() *KnowledgeLink {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *UpdateKnowledgeLinkRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteKnowledgeLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKnowledgeLinkRequest) Reset() {
	*x = DeleteKnowledgeLinkRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKnowledgeLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeLinkRequest) ProtoMessage() {}

func (x *DeleteKnowledgeLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteKnowledgeLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBacklinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Page          *Pagination            `protobuf:"bytes,10,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBacklinksRequest) Reset() {
	*x = GetBacklinksRequest{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBacklinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBacklinksRequest) ProtoMessage() {}

func (x *GetBacklinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBacklinksRequest.ProtoReflect.Descriptor instead.
func (*GetBacklinksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{30}
}

func (x *GetBacklinksRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *GetBacklinksRequest) GetPage() *Pagination {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetBacklinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KnowledgeLink       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBacklinksResponse) Reset() {
	*x = GetBacklinksResponse{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBacklinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBacklinksResponse) ProtoMessage() {}

func (x *GetBacklinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBacklinksResponse.ProtoReflect.Descriptor instead.
func (*GetBacklinksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{31}
}

func (x *GetBacklinksResponse) GetItems() []*KnowledgeLink {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetBacklinksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Utility Messages
type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Components    map[string]string      `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_knowledge_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_knowledge_proto_rawDescGZIP(), []int{32}
}

func (x *HealthStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthStatus) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

var File_api_proto_v1_knowledge_proto protoreflect.FileDescriptor

const file_api_proto_v1_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/v1/knowledge.proto\x12\fknowledge.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"H\n" +
	"\n" +
	"Pagination\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x96\x01\n" +
	"\n" +
	"SpaceStats\x12#\n" +
	"\rcontent_count\x18\x01 \x01(\x03R\fcontentCount\x12\x1d\n" +
	"\n" +
	"link_count\x18\x02 \x01(\x03R\tlinkCount\x12D\n" +
	"\x10last_activity_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastActivityAt\"\x90\x02\n" +
	"\x05Space\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12.\n" +
	"\x05stats\x18\n" +
	" \x01(\v2\x18.knowledge.v1.SpaceStatsR\x05stats\x129\n" +
	"\n" +
	"created_at\x18b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18c \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8d\x04\n" +
	"\rContentSource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.knowledge.v1.ContentStatusR\x06status\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12,\n" +
	"\x12original_blob_hash\x18\t \x01(\tR\x10originalBlobHash\x12.\n" +
	"\x13processed_blob_hash\x18\n" +
	" \x01(\tR\x11processedBlobHash\x12'\n" +
	"\x0fcontent_summary\x18\v \x01(\tR\x0econtentSummary\x12\x1a\n" +
	"\bkeywords\x18\f \x03(\tR\bkeywords\x129\n" +
	"\n" +
	"created_at\x18b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18c \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xba\x02\n" +
	"\rKnowledgeLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0ffrom_content_id\x18\x02 \x01(\tR\rfromContentId\x12\"\n" +
	"\rto_content_id\x18\x03 \x01(\tR\vtoContentId\x12?\n" +
	"\rrelation_type\x18\x04 \x01(\x0e2\x1a.knowledge.v1.RelationTypeR\frelationType\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\x129\n" +
	"\n" +
	"created_at\x18b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18c \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"_\n" +
	"\x0eContentPreview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12'\n" +
	"\x0fcontent_summary\x18\x03 \x01(\tR\x0econtentSummary\"\xd6\x02\n" +
	"\x15EnrichedKnowledgeLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04from\x18\x02 \x01(\v2\x1c.knowledge.v1.ContentPreviewR\x04from\x12,\n" +
	"\x02to\x18\x03 \x01(\v2\x1c.knowledge.v1.ContentPreviewR\x02to\x12?\n" +
	"\rrelation_type\x18\x04 \x01(\x0e2\x1a.knowledge.v1.RelationTypeR\frelationType\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\x129\n" +
	"\n" +
	"created_at\x18b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18c \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"L\n" +
	"\x12CreateSpaceRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"!\n" +
	"\x0fGetSpaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc9\x03\n" +
	"\x11ListSpacesRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords\x12!\n" +
	"\faccess_level\x18\x04 \x01(\tR\vaccessLevel\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12?\n" +
	"\rcreated_after\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fcreatedAfter\x12A\n" +
	"\x0ecreated_before\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rcreatedBefore\x12?\n" +
	"\rupdated_after\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\fupdatedAfter\x12A\n" +
	"\x0eupdated_before\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rupdatedBefore\x12,\n" +
	"\x04page\x18\n" +
	" \x01(\v2\x18.knowledge.v1.PaginationR\x04page\"g\n" +
	"\x12ListSpacesResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.knowledge.v1.SpaceR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x8c\x01\n" +
	"\x12UpdateSpaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x05space\x18\x02 \x01(\v2\x13.knowledge.v1.SpaceR\x05space\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"[\n" +
	"\x12DeleteSpaceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vhard_delete\x18\x02 \x01(\bR\n" +
	"hardDelete\x12\x14\n" +
	"\x05force\x18\x03 \x01(\bR\x05force\"\xe4\x01\n" +
	"\x16CreateUploadURLRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12A\n" +
	"\vobject_kind\x18\x06 \x01(\x0e2 .knowledge.v1.DownloadObjectKindR\n" +
	"objectKind\"\xd6\x01\n" +
	"\x17CreateUploadURLResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12B\n" +
	"\x0econtent_source\x18\n" +
	" \x01(\v2\x1b.knowledge.v1.ContentSourceR\rcontentSource\"\xa2\x01\n" +
	"\x14ConfirmUploadRequest\x12*\n" +
	"\x11content_source_id\x18\x01 \x01(\tR\x0fcontentSourceId\x12A\n" +
	"\vobject_kind\x18\x02 \x01(\x0e2 .knowledge.v1.DownloadObjectKindR\n" +
	"objectKind\x12\x1b\n" +
	"\tblob_hash\x18\x03 \x01(\tR\bblobHash\")\n" +
	"\x17GetContentSourceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x99\x01\n" +
	"\x19ListContentSourcesRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.knowledge.v1.ContentStatusR\x06status\x12,\n" +
	"\x04page\x18\n" +
	" \x01(\v2\x18.knowledge.v1.PaginationR\x04page\"w\n" +
	"\x1aListContentSourcesResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.knowledge.v1.ContentSourceR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xbc\x01\n" +
	" UpdateContentSourceStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.knowledge.v1.ContentStatusR\x06status\x12.\n" +
	"\x13processed_blob_hash\x18\x03 \x01(\tR\x11processedBlobHash\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xb4\x01\n" +
	"\x1aGenerateDownloadURLRequest\x12*\n" +
	"\x11content_source_id\x18\x01 \x01(\tR\x0fcontentSourceId\x12'\n" +
	"\x0fexpires_seconds\x18\x02 \x01(\x05R\x0eexpiresSeconds\x12A\n" +
	"\vobject_kind\x18\x03 \x01(\x0e2 .knowledge.v1.DownloadObjectKindR\n" +
	"objectKind\"\x89\x01\n" +
	"\x1bGenerateDownloadURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1d\n" +
	"\n" +
	"object_key\x18\x03 \x01(\tR\tobjectKey\"\xc1\x01\n" +
	"\x1aCreateKnowledgeLinkRequest\x12&\n" +
	"\x0ffrom_content_id\x18\x01 \x01(\tR\rfromContentId\x12\"\n" +
	"\rto_content_id\x18\x02 \x01(\tR\vtoContentId\x12?\n" +
	"\rrelation_type\x18\x03 \x01(\x0e2\x1a.knowledge.v1.RelationTypeR\frelationType\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\")\n" +
	"\x17GetKnowledgeLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe4\x01\n" +
	"\x19ListKnowledgeLinksRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x129\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x1b.knowledge.v1.LinkDirectionR\tdirection\x12?\n" +
	"\rrelation_type\x18\x03 \x01(\x0e2\x1a.knowledge.v1.RelationTypeR\frelationType\x12,\n" +
	"\x04page\x18\n" +
	" \x01(\v2\x18.knowledge.v1.PaginationR\x04page\"\x7f\n" +
	"\x1aListKnowledgeLinksResponse\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.knowledge.v1.EnrichedKnowledgeLinkR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xa4\x01\n" +
	"\x18ListAllSpaceLinksRequest\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12?\n" +
	"\rrelation_type\x18\x02 \x01(\x0e2\x1a.knowledge.v1.RelationTypeR\frelationType\x12,\n" +
	"\x04page\x18\n" +
	" \x01(\v2\x18.knowledge.v1.PaginationR\x04page\"v\n" +
	"\x19ListAllSpaceLinksResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.knowledge.v1.KnowledgeLinkR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x9a\x01\n" +
	"\x1aUpdateKnowledgeLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x04link\x18\x02 \x01(\v2\x1b.knowledge.v1.KnowledgeLinkR\x04link\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\",\n" +
	"\x1aDeleteKnowledgeLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"b\n" +
	"\x13GetBacklinksRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\x12,\n" +
	"\x04page\x18\n" +
	" \x01(\v2\x18.knowledge.v1.PaginationR\x04page\"q\n" +
	"\x14GetBacklinksResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.knowledge.v1.KnowledgeLinkR\x05items\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xb1\x01\n" +
	"\fHealthStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12J\n" +
	"\n" +
	"components\x18\x02 \x03(\v2*.knowledge.v1.HealthStatus.ComponentsEntryR\n" +
	"components\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*w\n" +
	"\rContentStatus\x12\x1e\n" +
	"\x1aCONTENT_STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tUPLOADING\x10\x01\x12\f\n" +
	"\bUPLOADED\x10\x02\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\x03\x12\r\n" +
	"\tPROCESSED\x10\x04\x12\n" +
	"\n" +
	"\x06FAILED\x10\x05*e\n" +
	"\fRelationType\x12\x1d\n" +
	"\x19RELATION_TYPE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"REFERENCES\x10\x01\x12\f\n" +
	"\bCONTAINS\x10\x02\x12\v\n" +
	"\aRELATED\x10\x03\x12\v\n" +
	"\aFOLLOWS\x10\x04*T\n" +
	"\rLinkDirection\x12\x1e\n" +
	"\x1aLINK_DIRECTION_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aINBOUND\x10\x01\x12\f\n" +
	"\bOUTBOUND\x10\x02\x12\b\n" +
	"\x04BOTH\x10\x03*\x81\x01\n" +
	"\x12DownloadObjectKind\x12$\n" +
	" DOWNLOAD_OBJECT_KIND_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dDOWNLOAD_OBJECT_KIND_ORIGINAL\x10\x01\x12\"\n" +
	"\x1eDOWNLOAD_OBJECT_KIND_PROCESSED\x10\x022\x9b\r\n" +
	"\x10KnowledgeService\x12D\n" +
	"\vCreateSpace\x12 .knowledge.v1.CreateSpaceRequest\x1a\x13.knowledge.v1.Space\x12>\n" +
	"\bGetSpace\x12\x1d.knowledge.v1.GetSpaceRequest\x1a\x13.knowledge.v1.Space\x12O\n" +
	"\n" +
	"ListSpaces\x12\x1f.knowledge.v1.ListSpacesRequest\x1a .knowledge.v1.ListSpacesResponse\x12D\n" +
	"\vUpdateSpace\x12 .knowledge.v1.UpdateSpaceRequest\x1a\x13.knowledge.v1.Space\x12G\n" +
	"\vDeleteSpace\x12 .knowledge.v1.DeleteSpaceRequest\x1a\x16.google.protobuf.Empty\x12^\n" +
	"\x0fCreateUploadURL\x12$.knowledge.v1.CreateUploadURLRequest\x1a%.knowledge.v1.CreateUploadURLResponse\x12P\n" +
	"\rConfirmUpload\x12\".knowledge.v1.ConfirmUploadRequest\x1a\x1b.knowledge.v1.ContentSource\x12V\n" +
	"\x10GetContentSource\x12%.knowledge.v1.GetContentSourceRequest\x1a\x1b.knowledge.v1.ContentSource\x12g\n" +
	"\x12ListContentSources\x12'.knowledge.v1.ListContentSourcesRequest\x1a(.knowledge.v1.ListContentSourcesResponse\x12h\n" +
	"\x19UpdateContentSourceStatus\x12..knowledge.v1.UpdateContentSourceStatusRequest\x1a\x1b.knowledge.v1.ContentSource\x12j\n" +
	"\x13GenerateDownloadURL\x12(.knowledge.v1.GenerateDownloadURLRequest\x1a).knowledge.v1.GenerateDownloadURLResponse\x12\\\n" +
	"\x13CreateKnowledgeLink\x12(.knowledge.v1.CreateKnowledgeLinkRequest\x1a\x1b.knowledge.v1.KnowledgeLink\x12^\n" +
	"\x10GetKnowledgeLink\x12%.knowledge.v1.GetKnowledgeLinkRequest\x1a#.knowledge.v1.EnrichedKnowledgeLink\x12g\n" +
	"\x12ListKnowledgeLinks\x12'.knowledge.v1.ListKnowledgeLinksRequest\x1a(.knowledge.v1.ListKnowledgeLinksResponse\x12d\n" +
	"\x11ListAllSpaceLinks\x12&.knowledge.v1.ListAllSpaceLinksRequest\x1a'.knowledge.v1.ListAllSpaceLinksResponse\x12\\\n" +
	"\x13UpdateKnowledgeLink\x12(.knowledge.v1.UpdateKnowledgeLinkRequest\x1a\x1b.knowledge.v1.KnowledgeLink\x12W\n" +
	"\x13DeleteKnowledgeLink\x12(.knowledge.v1.DeleteKnowledgeLinkRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\fGetBacklinks\x12!.knowledge.v1.GetBacklinksRequest\x1a\".knowledge.v1.GetBacklinksResponse\x12=\n" +
	"\aHealthz\x12\x16.google.protobuf.Empty\x1a\x1a.knowledge.v1.HealthStatusB,Z*demo/ms_knowledge/api/proto/v1;knowledgev1b\x06proto3"

var (
	file_api_proto_v1_knowledge_proto_rawDescOnce sync.Once
	file_api_proto_v1_knowledge_proto_rawDescData []byte
)

func file_api_proto_v1_knowledge_proto_rawDescGZIP() []byte {
	file_api_proto_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_knowledge_proto_rawDesc), len(file_api_proto_v1_knowledge_proto_rawDesc)))
	})
	return file_api_proto_v1_knowledge_proto_rawDescData
}

var file_api_proto_v1_knowledge_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_proto_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_api_proto_v1_knowledge_proto_goTypes = []any{
	(ContentStatus)(0),                       // 0: knowledge.v1.ContentStatus
	(RelationType)(0),                        // 1: knowledge.v1.RelationType
	(LinkDirection)(0),                       // 2: knowledge.v1.LinkDirection
	(DownloadObjectKind)(0),                  // 3: knowledge.v1.DownloadObjectKind
	(*Pagination)(nil),                       // 4: knowledge.v1.Pagination
	(*SpaceStats)(nil),                       // 5: knowledge.v1.SpaceStats
	(*Space)(nil),                            // 6: knowledge.v1.Space
	(*ContentSource)(nil),                    // 7: knowledge.v1.ContentSource
	(*KnowledgeLink)(nil),                    // 8: knowledge.v1.KnowledgeLink
	(*ContentPreview)(nil),                   // 9: knowledge.v1.ContentPreview
	(*EnrichedKnowledgeLink)(nil),            // 10: knowledge.v1.EnrichedKnowledgeLink
	(*CreateSpaceRequest)(nil),               // 11: knowledge.v1.CreateSpaceRequest
	(*GetSpaceRequest)(nil),                  // 12: knowledge.v1.GetSpaceRequest
	(*ListSpacesRequest)(nil),                // 13: knowledge.v1.ListSpacesRequest
	(*ListSpacesResponse)(nil),               // 14: knowledge.v1.ListSpacesResponse
	(*UpdateSpaceRequest)(nil),               // 15: knowledge.v1.UpdateSpaceRequest
	(*DeleteSpaceRequest)(nil),               // 16: knowledge.v1.DeleteSpaceRequest
	(*CreateUploadURLRequest)(nil),           // 17: knowledge.v1.CreateUploadURLRequest
	(*CreateUploadURLResponse)(nil),          // 18: knowledge.v1.CreateUploadURLResponse
	(*ConfirmUploadRequest)(nil),             // 19: knowledge.v1.ConfirmUploadRequest
	(*GetContentSourceRequest)(nil),          // 20: knowledge.v1.GetContentSourceRequest
	(*ListContentSourcesRequest)(nil),        // 21: knowledge.v1.ListContentSourcesRequest
	(*ListContentSourcesResponse)(nil),       // 22: knowledge.v1.ListContentSourcesResponse
	(*UpdateContentSourceStatusRequest)(nil), // 23: knowledge.v1.UpdateContentSourceStatusRequest
	(*GenerateDownloadURLRequest)(nil),       // 24: knowledge.v1.GenerateDownloadURLRequest
	(*GenerateDownloadURLResponse)(nil),      // 25: knowledge.v1.GenerateDownloadURLResponse
	(*CreateKnowledgeLinkRequest)(nil),       // 26: knowledge.v1.CreateKnowledgeLinkRequest
	(*GetKnowledgeLinkRequest)(nil),          // 27: knowledge.v1.GetKnowledgeLinkRequest
	(*ListKnowledgeLinksRequest)(nil),        // 28: knowledge.v1.ListKnowledgeLinksRequest
	(*ListKnowledgeLinksResponse)(nil),       // 29: knowledge.v1.ListKnowledgeLinksResponse
	(*ListAllSpaceLinksRequest)(nil),         // 30: knowledge.v1.ListAllSpaceLinksRequest
	(*ListAllSpaceLinksResponse)(nil),        // 31: knowledge.v1.ListAllSpaceLinksResponse
	(*UpdateKnowledgeLinkRequest)(nil),       // 32: knowledge.v1.UpdateKnowledgeLinkRequest
	(*DeleteKnowledgeLinkRequest)(nil),       // 33: knowledge.v1.DeleteKnowledgeLinkRequest
	(*GetBacklinksRequest)(nil),              // 34: knowledge.v1.GetBacklinksRequest
	(*GetBacklinksResponse)(nil),             // 35: knowledge.v1.GetBacklinksResponse
	(*HealthStatus)(nil),                     // 36: knowledge.v1.HealthStatus
	nil,                                      // 37: knowledge.v1.HealthStatus.ComponentsEntry
	(*timestamppb.Timestamp)(nil),            // 38: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),            // 39: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                    // 40: google.protobuf.Empty
}
var file_api_proto_v1_knowledge_proto_depIdxs = []int32{
	38, // 0: knowledge.v1.SpaceStats.last_activity_at:type_name -> google.protobuf.Timestamp
	5,  // 1: knowledge.v1.Space.stats:type_name -> knowledge.v1.SpaceStats
	38, // 2: knowledge.v1.Space.created_at:type_name -> google.protobuf.Timestamp
	38, // 3: knowledge.v1.Space.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: knowledge.v1.ContentSource.status:type_name -> knowledge.v1.ContentStatus
	38, // 5: knowledge.v1.ContentSource.created_at:type_name -> google.protobuf.Timestamp
	38, // 6: knowledge.v1.ContentSource.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 7: knowledge.v1.KnowledgeLink.relation_type:type_name -> knowledge.v1.RelationType
	38, // 8: knowledge.v1.KnowledgeLink.created_at:type_name -> google.protobuf.Timestamp
	38, // 9: knowledge.v1.KnowledgeLink.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 10: knowledge.v1.EnrichedKnowledgeLink.from:type_name -> knowledge.v1.ContentPreview
	9,  // 11: knowledge.v1.EnrichedKnowledgeLink.to:type_name -> knowledge.v1.ContentPreview
	1,  // 12: knowledge.v1.EnrichedKnowledgeLink.relation_type:type_name -> knowledge.v1.RelationType
	38, // 13: knowledge.v1.EnrichedKnowledgeLink.created_at:type_name -> google.protobuf.Timestamp
	38, // 14: knowledge.v1.EnrichedKnowledgeLink.updated_at:type_name -> google.protobuf.Timestamp
	38, // 15: knowledge.v1.ListSpacesRequest.created_after:type_name -> google.protobuf.Timestamp
	38, // 16: knowledge.v1.ListSpacesRequest.created_before:type_name -> google.protobuf.Timestamp
	38, // 17: knowledge.v1.ListSpacesRequest.updated_after:type_name -> google.protobuf.Timestamp
	38, // 18: knowledge.v1.ListSpacesRequest.updated_before:type_name -> google.protobuf.Timestamp
	4,  // 19: knowledge.v1.ListSpacesRequest.page:type_name -> knowledge.v1.Pagination
	6,  // 20: knowledge.v1.ListSpacesResponse.items:type_name -> knowledge.v1.Space
	6,  // 21: knowledge.v1.UpdateSpaceRequest.space:type_name -> knowledge.v1.Space
	39, // 22: knowledge.v1.UpdateSpaceRequest.update_mask:type_name -> google.protobuf.FieldMask
	3,  // 23: knowledge.v1.CreateUploadURLRequest.object_kind:type_name -> knowledge.v1.DownloadObjectKind
	38, // 24: knowledge.v1.CreateUploadURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	7,  // 25: knowledge.v1.CreateUploadURLResponse.content_source:type_name -> knowledge.v1.ContentSource
	3,  // 26: knowledge.v1.ConfirmUploadRequest.object_kind:type_name -> knowledge.v1.DownloadObjectKind
	0,  // 27: knowledge.v1.ListContentSourcesRequest.status:type_name -> knowledge.v1.ContentStatus
	4,  // 28: knowledge.v1.ListContentSourcesRequest.page:type_name -> knowledge.v1.Pagination
	7,  // 29: knowledge.v1.ListContentSourcesResponse.items:type_name -> knowledge.v1.ContentSource
	0,  // 30: knowledge.v1.UpdateContentSourceStatusRequest.status:type_name -> knowledge.v1.ContentStatus
	3,  // 31: knowledge.v1.GenerateDownloadURLRequest.object_kind:type_name -> knowledge.v1.DownloadObjectKind
	38, // 32: knowledge.v1.GenerateDownloadURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 33: knowledge.v1.CreateKnowledgeLinkRequest.relation_type:type_name -> knowledge.v1.RelationType
	2,  // 34: knowledge.v1.ListKnowledgeLinksRequest.direction:type_name -> knowledge.v1.LinkDirection
	1,  // 35: knowledge.v1.ListKnowledgeLinksRequest.relation_type:type_name -> knowledge.v1.RelationType
	4,  // 36: knowledge.v1.ListKnowledgeLinksRequest.page:type_name -> knowledge.v1.Pagination
	10, // 37: knowledge.v1.ListKnowledgeLinksResponse.items:type_name -> knowledge.v1.EnrichedKnowledgeLink
	1,  // 38: knowledge.v1.ListAllSpaceLinksRequest.relation_type:type_name -> knowledge.v1.RelationType
	4,  // 39: knowledge.v1.ListAllSpaceLinksRequest.page:type_name -> knowledge.v1.Pagination
	8,  // 40: knowledge.v1.ListAllSpaceLinksResponse.items:type_name -> knowledge.v1.KnowledgeLink
	8,  // 41: knowledge.v1.UpdateKnowledgeLinkRequest.link:type_name -> knowledge.v1.KnowledgeLink
	39, // 42: knowledge.v1.UpdateKnowledgeLinkRequest.update_mask:type_name -> google.protobuf.FieldMask
	4,  // 43: knowledge.v1.GetBacklinksRequest.page:type_name -> knowledge.v1.Pagination
	8,  // 44: knowledge.v1.GetBacklinksResponse.items:type_name -> knowledge.v1.KnowledgeLink
	37, // 45: knowledge.v1.HealthStatus.components:type_name -> knowledge.v1.HealthStatus.ComponentsEntry
	11, // 46: knowledge.v1.KnowledgeService.CreateSpace:input_type -> knowledge.v1.CreateSpaceRequest
	12, // 47: knowledge.v1.KnowledgeService.GetSpace:input_type -> knowledge.v1.GetSpaceRequest
	13, // 48: knowledge.v1.KnowledgeService.ListSpaces:input_type -> knowledge.v1.ListSpacesRequest
	15, // 49: knowledge.v1.KnowledgeService.UpdateSpace:input_type -> knowledge.v1.UpdateSpaceRequest
	16, // 50: knowledge.v1.KnowledgeService.DeleteSpace:input_type -> knowledge.v1.DeleteSpaceRequest
	17, // 51: knowledge.v1.KnowledgeService.CreateUploadURL:input_type -> knowledge.v1.CreateUploadURLRequest
	19, // 52: knowledge.v1.KnowledgeService.ConfirmUpload:input_type -> knowledge.v1.ConfirmUploadRequest
	20, // 53: knowledge.v1.KnowledgeService.GetContentSource:input_type -> knowledge.v1.GetContentSourceRequest
	21, // 54: knowledge.v1.KnowledgeService.ListContentSources:input_type -> knowledge.v1.ListContentSourcesRequest
	23, // 55: knowledge.v1.KnowledgeService.UpdateContentSourceStatus:input_type -> knowledge.v1.UpdateContentSourceStatusRequest
	24, // 56: knowledge.v1.KnowledgeService.GenerateDownloadURL:input_type -> knowledge.v1.GenerateDownloadURLRequest
	26, // 57: knowledge.v1.KnowledgeService.CreateKnowledgeLink:input_type -> knowledge.v1.CreateKnowledgeLinkRequest
	27, // 58: knowledge.v1.KnowledgeService.GetKnowledgeLink:input_type -> knowledge.v1.GetKnowledgeLinkRequest
	28, // 59: knowledge.v1.KnowledgeService.ListKnowledgeLinks:input_type -> knowledge.v1.ListKnowledgeLinksRequest
	30, // 60: knowledge.v1.KnowledgeService.ListAllSpaceLinks:input_type -> knowledge.v1.ListAllSpaceLinksRequest
	32, // 61: knowledge.v1.KnowledgeService.UpdateKnowledgeLink:input_type -> knowledge.v1.UpdateKnowledgeLinkRequest
	33, // 62: knowledge.v1.KnowledgeService.DeleteKnowledgeLink:input_type -> knowledge.v1.DeleteKnowledgeLinkRequest
	34, // 63: knowledge.v1.KnowledgeService.GetBacklinks:input_type -> knowledge.v1.GetBacklinksRequest
	40, // 64: knowledge.v1.KnowledgeService.Healthz:input_type -> google.protobuf.Empty
	6,  // 65: knowledge.v1.KnowledgeService.CreateSpace:output_type -> knowledge.v1.Space
	6,  // 66: knowledge.v1.KnowledgeService.GetSpace:output_type -> knowledge.v1.Space
	14, // 67: knowledge.v1.KnowledgeService.ListSpaces:output_type -> knowledge.v1.ListSpacesResponse
	6,  // 68: knowledge.v1.KnowledgeService.UpdateSpace:output_type -> knowledge.v1.Space
	40, // 69: knowledge.v1.KnowledgeService.DeleteSpace:output_type -> google.protobuf.Empty
	18, // 70: knowledge.v1.KnowledgeService.CreateUploadURL:output_type -> knowledge.v1.CreateUploadURLResponse
	7,  // 71: knowledge.v1.KnowledgeService.ConfirmUpload:output_type -> knowledge.v1.ContentSource
	7,  // 72: knowledge.v1.KnowledgeService.GetContentSource:output_type -> knowledge.v1.ContentSource
	22, // 73: knowledge.v1.KnowledgeService.ListContentSources:output_type -> knowledge.v1.ListContentSourcesResponse
	7,  // 74: knowledge.v1.KnowledgeService.UpdateContentSourceStatus:output_type -> knowledge.v1.ContentSource
	25, // 75: knowledge.v1.KnowledgeService.GenerateDownloadURL:output_type -> knowledge.v1.GenerateDownloadURLResponse
	8,  // 76: knowledge.v1.KnowledgeService.CreateKnowledgeLink:output_type -> knowledge.v1.KnowledgeLink
	10, // 77: knowledge.v1.KnowledgeService.GetKnowledgeLink:output_type -> knowledge.v1.EnrichedKnowledgeLink
	29, // 78: knowledge.v1.KnowledgeService.ListKnowledgeLinks:output_type -> knowledge.v1.ListKnowledgeLinksResponse
	31, // 79: knowledge.v1.KnowledgeService.ListAllSpaceLinks:output_type -> knowledge.v1.ListAllSpaceLinksResponse
	8,  // 80: knowledge.v1.KnowledgeService.UpdateKnowledgeLink:output_type -> knowledge.v1.KnowledgeLink
	40, // 81: knowledge.v1.KnowledgeService.DeleteKnowledgeLink:output_type -> google.protobuf.Empty
	35, // 82: knowledge.v1.KnowledgeService.GetBacklinks:output_type -> knowledge.v1.GetBacklinksResponse
	36, // 83: knowledge.v1.KnowledgeService.Healthz:output_type -> knowledge.v1.HealthStatus
	65, // [65:84] is the sub-list for method output_type
	46, // [46:65] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_api_proto_v1_knowledge_proto_init() }
func file_api_proto_v1_knowledge_proto_init() {
	if File_api_proto_v1_knowledge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_knowledge_proto_rawDesc), len(file_api_proto_v1_knowledge_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_knowledge_proto_depIdxs,
		EnumInfos:         file_api_proto_v1_knowledge_proto_enumTypes,
		MessageInfos:      file_api_proto_v1_knowledge_proto_msgTypes,
	}.Build()
	File_api_proto_v1_knowledge_proto = out.File
	file_api_proto_v1_knowledge_proto_goTypes = nil
	file_api_proto_v1_knowledge_proto_depIdxs = nil
}
