// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "clerk_user_id", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "full_name", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Nullable: true},
		{Name: "profile_picture_url", Type: field.TypeString, Nullable: true},
		{Name: "storage_used_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "storage_quota_bytes", Type: field.TypeInt64, Default: 5368709120},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserPreferencesColumns holds the columns for the "user_preferences" table.
	UserPreferencesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "theme", Type: field.TypeString, Default: "auto"},
		{Name: "language", Type: field.TypeString, Default: "en"},
		{Name: "timezone", Type: field.TypeString, Nullable: true},
		{Name: "canvas_settings", Type: field.TypeJSON, Nullable: true},
		{Name: "notification_settings", Type: field.TypeJSON, Nullable: true},
		{Name: "accessibility_settings", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_preferences", Type: field.TypeUUID, Unique: true},
	}
	// UserPreferencesTable holds the schema information for the "user_preferences" table.
	UserPreferencesTable = &schema.Table{
		Name:       "user_preferences",
		Columns:    UserPreferencesColumns,
		PrimaryKey: []*schema.Column{UserPreferencesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_preferences_users_preferences",
				Columns:    []*schema.Column{UserPreferencesColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
		UserPreferencesTable,
	}
)

func init() {
	UserPreferencesTable.ForeignKeys[0].RefTable = UsersTable
}
