// Code generated by ent, DO NOT EDIT.

package contentsource

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the contentsource type in the database.
	Label = "content_source"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSpaceID holds the string denoting the space_id field in the database.
	FieldSpaceID = "space_id"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldMediaType holds the string denoting the media_type field in the database.
	FieldMediaType = "media_type"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSizeBytes holds the string denoting the size_bytes field in the database.
	FieldSizeBytes = "size_bytes"
	// FieldOriginalBlobHash holds the string denoting the original_blob_hash field in the database.
	FieldOriginalBlobHash = "original_blob_hash"
	// FieldProcessedBlobHash holds the string denoting the processed_blob_hash field in the database.
	FieldProcessedBlobHash = "processed_blob_hash"
	// FieldContentSummary holds the string denoting the content_summary field in the database.
	FieldContentSummary = "content_summary"
	// FieldKeywords holds the string denoting the keywords field in the database.
	FieldKeywords = "keywords"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeSpace holds the string denoting the space edge name in mutations.
	EdgeSpace = "space"
	// Table holds the table name of the contentsource in the database.
	Table = "content_sources"
	// SpaceTable is the table that holds the space relation/edge.
	SpaceTable = "content_sources"
	// SpaceInverseTable is the table name for the Space entity.
	// It exists in this package in order to avoid circular dependency with the "space" package.
	SpaceInverseTable = "spaces"
	// SpaceColumn is the table column denoting the space relation/edge.
	SpaceColumn = "space_id"
)

// Columns holds all SQL columns for contentsource fields.
var Columns = []string{
	FieldID,
	FieldSpaceID,
	FieldOwnerID,
	FieldTitle,
	FieldMediaType,
	FieldSource,
	FieldStatus,
	FieldSizeBytes,
	FieldOriginalBlobHash,
	FieldProcessedBlobHash,
	FieldContentSummary,
	FieldKeywords,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultSizeBytes holds the default value on creation for the "size_bytes" field.
	DefaultSizeBytes int64
	// OriginalBlobHashValidator is a validator for the "original_blob_hash" field. It is called by the builders before save.
	OriginalBlobHashValidator func(string) error
	// ProcessedBlobHashValidator is a validator for the "processed_blob_hash" field. It is called by the builders before save.
	ProcessedBlobHashValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ContentSource queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySpaceID orders the results by the space_id field.
func BySpaceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpaceID, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByMediaType orders the results by the media_type field.
func ByMediaType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMediaType, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySizeBytes orders the results by the size_bytes field.
func BySizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSizeBytes, opts...).ToFunc()
}

// ByOriginalBlobHash orders the results by the original_blob_hash field.
func ByOriginalBlobHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOriginalBlobHash, opts...).ToFunc()
}

// ByProcessedBlobHash orders the results by the processed_blob_hash field.
func ByProcessedBlobHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProcessedBlobHash, opts...).ToFunc()
}

// ByContentSummary orders the results by the content_summary field.
func ByContentSummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentSummary, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// BySpaceField orders the results by space field.
func BySpaceField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSpaceStep(), sql.OrderByField(field, opts...))
	}
}
func newSpaceStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SpaceInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SpaceTable, SpaceColumn),
	)
}
