// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ContentSourcesColumns holds the columns for the "content_sources" table.
	ContentSourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "owner_id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "media_type", Type: field.TypeString},
		{Name: "source", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "UPLOADING"},
		{Name: "size_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "original_blob_hash", Type: field.TypeString, Size: 64},
		{Name: "processed_blob_hash", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "content_summary", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "keywords", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "space_id", Type: field.TypeUUID},
	}
	// ContentSourcesTable holds the schema information for the "content_sources" table.
	ContentSourcesTable = &schema.Table{
		Name:       "content_sources",
		Columns:    ContentSourcesColumns,
		PrimaryKey: []*schema.Column{ContentSourcesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "content_sources_spaces_content_sources",
				Columns:    []*schema.Column{ContentSourcesColumns[14]},
				RefColumns: []*schema.Column{SpacesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SpacesColumns holds the columns for the "spaces" table.
	SpacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "icon", Type: field.TypeString, Nullable: true},
		{Name: "cover_image", Type: field.TypeString, Nullable: true},
		{Name: "keywords", Type: field.TypeJSON, Nullable: true},
		{Name: "owner_id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeUUID},
		{Name: "last_updated_at", Type: field.TypeTime},
		{Name: "last_updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "document_count", Type: field.TypeInt, Default: 0},
		{Name: "total_size_bytes", Type: field.TypeInt64, Default: 0},
		{Name: "storage_quota_bytes", Type: field.TypeInt64, Default: 1073741824},
		{Name: "access_level", Type: field.TypeString, Default: "private"},
		{Name: "guest_access_enabled", Type: field.TypeBool, Default: false},
		{Name: "guest_access_expiry", Type: field.TypeTime, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "processing_status", Type: field.TypeString, Default: "idle"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// SpacesTable holds the schema information for the "spaces" table.
	SpacesTable = &schema.Table{
		Name:       "spaces",
		Columns:    SpacesColumns,
		PrimaryKey: []*schema.Column{SpacesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ContentSourcesTable,
		SpacesTable,
	}
)

func init() {
	ContentSourcesTable.ForeignKeys[0].RefTable = SpacesTable
}
