// Code generated by ent, DO NOT EDIT.

package space

import (
	"demo/ms_knowledge/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldDescription, v))
}

// Icon applies equality check predicate on the "icon" field. It's identical to IconEQ.
func Icon(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldIcon, v))
}

// CoverImage applies equality check predicate on the "cover_image" field. It's identical to CoverImageEQ.
func CoverImage(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldCoverImage, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldOwnerID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldCreatedBy, v))
}

// LastUpdatedAt applies equality check predicate on the "last_updated_at" field. It's identical to LastUpdatedAtEQ.
func LastUpdatedAt(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldLastUpdatedAt, v))
}

// LastUpdatedBy applies equality check predicate on the "last_updated_by" field. It's identical to LastUpdatedByEQ.
func LastUpdatedBy(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldLastUpdatedBy, v))
}

// DocumentCount applies equality check predicate on the "document_count" field. It's identical to DocumentCountEQ.
func DocumentCount(v int) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldDocumentCount, v))
}

// TotalSizeBytes applies equality check predicate on the "total_size_bytes" field. It's identical to TotalSizeBytesEQ.
func TotalSizeBytes(v int64) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldTotalSizeBytes, v))
}

// StorageQuotaBytes applies equality check predicate on the "storage_quota_bytes" field. It's identical to StorageQuotaBytesEQ.
func StorageQuotaBytes(v int64) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldStorageQuotaBytes, v))
}

// AccessLevel applies equality check predicate on the "access_level" field. It's identical to AccessLevelEQ.
func AccessLevel(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldAccessLevel, v))
}

// GuestAccessEnabled applies equality check predicate on the "guest_access_enabled" field. It's identical to GuestAccessEnabledEQ.
func GuestAccessEnabled(v bool) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldGuestAccessEnabled, v))
}

// GuestAccessExpiry applies equality check predicate on the "guest_access_expiry" field. It's identical to GuestAccessExpiryEQ.
func GuestAccessExpiry(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldGuestAccessExpiry, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldStatus, v))
}

// ProcessingStatus applies equality check predicate on the "processing_status" field. It's identical to ProcessingStatusEQ.
func ProcessingStatus(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldProcessingStatus, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldDeletedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Space {
	return predicate.Space(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Space {
	return predicate.Space(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Space {
	return predicate.Space(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Space {
	return predicate.Space(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.Space {
	return predicate.Space(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.Space {
	return predicate.Space(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Space {
	return predicate.Space(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Space {
	return predicate.Space(sql.FieldContainsFold(FieldDescription, v))
}

// IconEQ applies the EQ predicate on the "icon" field.
func IconEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldIcon, v))
}

// IconNEQ applies the NEQ predicate on the "icon" field.
func IconNEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldIcon, v))
}

// IconIn applies the In predicate on the "icon" field.
func IconIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldIcon, vs...))
}

// IconNotIn applies the NotIn predicate on the "icon" field.
func IconNotIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldIcon, vs...))
}

// IconGT applies the GT predicate on the "icon" field.
func IconGT(v string) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldIcon, v))
}

// IconGTE applies the GTE predicate on the "icon" field.
func IconGTE(v string) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldIcon, v))
}

// IconLT applies the LT predicate on the "icon" field.
func IconLT(v string) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldIcon, v))
}

// IconLTE applies the LTE predicate on the "icon" field.
func IconLTE(v string) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldIcon, v))
}

// IconContains applies the Contains predicate on the "icon" field.
func IconContains(v string) predicate.Space {
	return predicate.Space(sql.FieldContains(FieldIcon, v))
}

// IconHasPrefix applies the HasPrefix predicate on the "icon" field.
func IconHasPrefix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasPrefix(FieldIcon, v))
}

// IconHasSuffix applies the HasSuffix predicate on the "icon" field.
func IconHasSuffix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasSuffix(FieldIcon, v))
}

// IconIsNil applies the IsNil predicate on the "icon" field.
func IconIsNil() predicate.Space {
	return predicate.Space(sql.FieldIsNull(FieldIcon))
}

// IconNotNil applies the NotNil predicate on the "icon" field.
func IconNotNil() predicate.Space {
	return predicate.Space(sql.FieldNotNull(FieldIcon))
}

// IconEqualFold applies the EqualFold predicate on the "icon" field.
func IconEqualFold(v string) predicate.Space {
	return predicate.Space(sql.FieldEqualFold(FieldIcon, v))
}

// IconContainsFold applies the ContainsFold predicate on the "icon" field.
func IconContainsFold(v string) predicate.Space {
	return predicate.Space(sql.FieldContainsFold(FieldIcon, v))
}

// CoverImageEQ applies the EQ predicate on the "cover_image" field.
func CoverImageEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldCoverImage, v))
}

// CoverImageNEQ applies the NEQ predicate on the "cover_image" field.
func CoverImageNEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldCoverImage, v))
}

// CoverImageIn applies the In predicate on the "cover_image" field.
func CoverImageIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldCoverImage, vs...))
}

// CoverImageNotIn applies the NotIn predicate on the "cover_image" field.
func CoverImageNotIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldCoverImage, vs...))
}

// CoverImageGT applies the GT predicate on the "cover_image" field.
func CoverImageGT(v string) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldCoverImage, v))
}

// CoverImageGTE applies the GTE predicate on the "cover_image" field.
func CoverImageGTE(v string) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldCoverImage, v))
}

// CoverImageLT applies the LT predicate on the "cover_image" field.
func CoverImageLT(v string) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldCoverImage, v))
}

// CoverImageLTE applies the LTE predicate on the "cover_image" field.
func CoverImageLTE(v string) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldCoverImage, v))
}

// CoverImageContains applies the Contains predicate on the "cover_image" field.
func CoverImageContains(v string) predicate.Space {
	return predicate.Space(sql.FieldContains(FieldCoverImage, v))
}

// CoverImageHasPrefix applies the HasPrefix predicate on the "cover_image" field.
func CoverImageHasPrefix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasPrefix(FieldCoverImage, v))
}

// CoverImageHasSuffix applies the HasSuffix predicate on the "cover_image" field.
func CoverImageHasSuffix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasSuffix(FieldCoverImage, v))
}

// CoverImageIsNil applies the IsNil predicate on the "cover_image" field.
func CoverImageIsNil() predicate.Space {
	return predicate.Space(sql.FieldIsNull(FieldCoverImage))
}

// CoverImageNotNil applies the NotNil predicate on the "cover_image" field.
func CoverImageNotNil() predicate.Space {
	return predicate.Space(sql.FieldNotNull(FieldCoverImage))
}

// CoverImageEqualFold applies the EqualFold predicate on the "cover_image" field.
func CoverImageEqualFold(v string) predicate.Space {
	return predicate.Space(sql.FieldEqualFold(FieldCoverImage, v))
}

// CoverImageContainsFold applies the ContainsFold predicate on the "cover_image" field.
func CoverImageContainsFold(v string) predicate.Space {
	return predicate.Space(sql.FieldContainsFold(FieldCoverImage, v))
}

// KeywordsIsNil applies the IsNil predicate on the "keywords" field.
func KeywordsIsNil() predicate.Space {
	return predicate.Space(sql.FieldIsNull(FieldKeywords))
}

// KeywordsNotNil applies the NotNil predicate on the "keywords" field.
func KeywordsNotNil() predicate.Space {
	return predicate.Space(sql.FieldNotNull(FieldKeywords))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldOwnerID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldCreatedBy, v))
}

// LastUpdatedAtEQ applies the EQ predicate on the "last_updated_at" field.
func LastUpdatedAtEQ(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldLastUpdatedAt, v))
}

// LastUpdatedAtNEQ applies the NEQ predicate on the "last_updated_at" field.
func LastUpdatedAtNEQ(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldLastUpdatedAt, v))
}

// LastUpdatedAtIn applies the In predicate on the "last_updated_at" field.
func LastUpdatedAtIn(vs ...time.Time) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldLastUpdatedAt, vs...))
}

// LastUpdatedAtNotIn applies the NotIn predicate on the "last_updated_at" field.
func LastUpdatedAtNotIn(vs ...time.Time) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldLastUpdatedAt, vs...))
}

// LastUpdatedAtGT applies the GT predicate on the "last_updated_at" field.
func LastUpdatedAtGT(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldLastUpdatedAt, v))
}

// LastUpdatedAtGTE applies the GTE predicate on the "last_updated_at" field.
func LastUpdatedAtGTE(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldLastUpdatedAt, v))
}

// LastUpdatedAtLT applies the LT predicate on the "last_updated_at" field.
func LastUpdatedAtLT(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldLastUpdatedAt, v))
}

// LastUpdatedAtLTE applies the LTE predicate on the "last_updated_at" field.
func LastUpdatedAtLTE(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldLastUpdatedAt, v))
}

// LastUpdatedByEQ applies the EQ predicate on the "last_updated_by" field.
func LastUpdatedByEQ(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldLastUpdatedBy, v))
}

// LastUpdatedByNEQ applies the NEQ predicate on the "last_updated_by" field.
func LastUpdatedByNEQ(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldLastUpdatedBy, v))
}

// LastUpdatedByIn applies the In predicate on the "last_updated_by" field.
func LastUpdatedByIn(vs ...uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldLastUpdatedBy, vs...))
}

// LastUpdatedByNotIn applies the NotIn predicate on the "last_updated_by" field.
func LastUpdatedByNotIn(vs ...uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldLastUpdatedBy, vs...))
}

// LastUpdatedByGT applies the GT predicate on the "last_updated_by" field.
func LastUpdatedByGT(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldLastUpdatedBy, v))
}

// LastUpdatedByGTE applies the GTE predicate on the "last_updated_by" field.
func LastUpdatedByGTE(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldLastUpdatedBy, v))
}

// LastUpdatedByLT applies the LT predicate on the "last_updated_by" field.
func LastUpdatedByLT(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldLastUpdatedBy, v))
}

// LastUpdatedByLTE applies the LTE predicate on the "last_updated_by" field.
func LastUpdatedByLTE(v uuid.UUID) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldLastUpdatedBy, v))
}

// LastUpdatedByIsNil applies the IsNil predicate on the "last_updated_by" field.
func LastUpdatedByIsNil() predicate.Space {
	return predicate.Space(sql.FieldIsNull(FieldLastUpdatedBy))
}

// LastUpdatedByNotNil applies the NotNil predicate on the "last_updated_by" field.
func LastUpdatedByNotNil() predicate.Space {
	return predicate.Space(sql.FieldNotNull(FieldLastUpdatedBy))
}

// DocumentCountEQ applies the EQ predicate on the "document_count" field.
func DocumentCountEQ(v int) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldDocumentCount, v))
}

// DocumentCountNEQ applies the NEQ predicate on the "document_count" field.
func DocumentCountNEQ(v int) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldDocumentCount, v))
}

// DocumentCountIn applies the In predicate on the "document_count" field.
func DocumentCountIn(vs ...int) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldDocumentCount, vs...))
}

// DocumentCountNotIn applies the NotIn predicate on the "document_count" field.
func DocumentCountNotIn(vs ...int) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldDocumentCount, vs...))
}

// DocumentCountGT applies the GT predicate on the "document_count" field.
func DocumentCountGT(v int) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldDocumentCount, v))
}

// DocumentCountGTE applies the GTE predicate on the "document_count" field.
func DocumentCountGTE(v int) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldDocumentCount, v))
}

// DocumentCountLT applies the LT predicate on the "document_count" field.
func DocumentCountLT(v int) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldDocumentCount, v))
}

// DocumentCountLTE applies the LTE predicate on the "document_count" field.
func DocumentCountLTE(v int) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldDocumentCount, v))
}

// TotalSizeBytesEQ applies the EQ predicate on the "total_size_bytes" field.
func TotalSizeBytesEQ(v int64) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldTotalSizeBytes, v))
}

// TotalSizeBytesNEQ applies the NEQ predicate on the "total_size_bytes" field.
func TotalSizeBytesNEQ(v int64) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldTotalSizeBytes, v))
}

// TotalSizeBytesIn applies the In predicate on the "total_size_bytes" field.
func TotalSizeBytesIn(vs ...int64) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldTotalSizeBytes, vs...))
}

// TotalSizeBytesNotIn applies the NotIn predicate on the "total_size_bytes" field.
func TotalSizeBytesNotIn(vs ...int64) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldTotalSizeBytes, vs...))
}

// TotalSizeBytesGT applies the GT predicate on the "total_size_bytes" field.
func TotalSizeBytesGT(v int64) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldTotalSizeBytes, v))
}

// TotalSizeBytesGTE applies the GTE predicate on the "total_size_bytes" field.
func TotalSizeBytesGTE(v int64) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldTotalSizeBytes, v))
}

// TotalSizeBytesLT applies the LT predicate on the "total_size_bytes" field.
func TotalSizeBytesLT(v int64) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldTotalSizeBytes, v))
}

// TotalSizeBytesLTE applies the LTE predicate on the "total_size_bytes" field.
func TotalSizeBytesLTE(v int64) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldTotalSizeBytes, v))
}

// StorageQuotaBytesEQ applies the EQ predicate on the "storage_quota_bytes" field.
func StorageQuotaBytesEQ(v int64) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldStorageQuotaBytes, v))
}

// StorageQuotaBytesNEQ applies the NEQ predicate on the "storage_quota_bytes" field.
func StorageQuotaBytesNEQ(v int64) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldStorageQuotaBytes, v))
}

// StorageQuotaBytesIn applies the In predicate on the "storage_quota_bytes" field.
func StorageQuotaBytesIn(vs ...int64) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldStorageQuotaBytes, vs...))
}

// StorageQuotaBytesNotIn applies the NotIn predicate on the "storage_quota_bytes" field.
func StorageQuotaBytesNotIn(vs ...int64) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldStorageQuotaBytes, vs...))
}

// StorageQuotaBytesGT applies the GT predicate on the "storage_quota_bytes" field.
func StorageQuotaBytesGT(v int64) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldStorageQuotaBytes, v))
}

// StorageQuotaBytesGTE applies the GTE predicate on the "storage_quota_bytes" field.
func StorageQuotaBytesGTE(v int64) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldStorageQuotaBytes, v))
}

// StorageQuotaBytesLT applies the LT predicate on the "storage_quota_bytes" field.
func StorageQuotaBytesLT(v int64) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldStorageQuotaBytes, v))
}

// StorageQuotaBytesLTE applies the LTE predicate on the "storage_quota_bytes" field.
func StorageQuotaBytesLTE(v int64) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldStorageQuotaBytes, v))
}

// AccessLevelEQ applies the EQ predicate on the "access_level" field.
func AccessLevelEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldAccessLevel, v))
}

// AccessLevelNEQ applies the NEQ predicate on the "access_level" field.
func AccessLevelNEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldAccessLevel, v))
}

// AccessLevelIn applies the In predicate on the "access_level" field.
func AccessLevelIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldAccessLevel, vs...))
}

// AccessLevelNotIn applies the NotIn predicate on the "access_level" field.
func AccessLevelNotIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldAccessLevel, vs...))
}

// AccessLevelGT applies the GT predicate on the "access_level" field.
func AccessLevelGT(v string) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldAccessLevel, v))
}

// AccessLevelGTE applies the GTE predicate on the "access_level" field.
func AccessLevelGTE(v string) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldAccessLevel, v))
}

// AccessLevelLT applies the LT predicate on the "access_level" field.
func AccessLevelLT(v string) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldAccessLevel, v))
}

// AccessLevelLTE applies the LTE predicate on the "access_level" field.
func AccessLevelLTE(v string) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldAccessLevel, v))
}

// AccessLevelContains applies the Contains predicate on the "access_level" field.
func AccessLevelContains(v string) predicate.Space {
	return predicate.Space(sql.FieldContains(FieldAccessLevel, v))
}

// AccessLevelHasPrefix applies the HasPrefix predicate on the "access_level" field.
func AccessLevelHasPrefix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasPrefix(FieldAccessLevel, v))
}

// AccessLevelHasSuffix applies the HasSuffix predicate on the "access_level" field.
func AccessLevelHasSuffix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasSuffix(FieldAccessLevel, v))
}

// AccessLevelEqualFold applies the EqualFold predicate on the "access_level" field.
func AccessLevelEqualFold(v string) predicate.Space {
	return predicate.Space(sql.FieldEqualFold(FieldAccessLevel, v))
}

// AccessLevelContainsFold applies the ContainsFold predicate on the "access_level" field.
func AccessLevelContainsFold(v string) predicate.Space {
	return predicate.Space(sql.FieldContainsFold(FieldAccessLevel, v))
}

// GuestAccessEnabledEQ applies the EQ predicate on the "guest_access_enabled" field.
func GuestAccessEnabledEQ(v bool) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldGuestAccessEnabled, v))
}

// GuestAccessEnabledNEQ applies the NEQ predicate on the "guest_access_enabled" field.
func GuestAccessEnabledNEQ(v bool) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldGuestAccessEnabled, v))
}

// GuestAccessExpiryEQ applies the EQ predicate on the "guest_access_expiry" field.
func GuestAccessExpiryEQ(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldGuestAccessExpiry, v))
}

// GuestAccessExpiryNEQ applies the NEQ predicate on the "guest_access_expiry" field.
func GuestAccessExpiryNEQ(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldGuestAccessExpiry, v))
}

// GuestAccessExpiryIn applies the In predicate on the "guest_access_expiry" field.
func GuestAccessExpiryIn(vs ...time.Time) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldGuestAccessExpiry, vs...))
}

// GuestAccessExpiryNotIn applies the NotIn predicate on the "guest_access_expiry" field.
func GuestAccessExpiryNotIn(vs ...time.Time) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldGuestAccessExpiry, vs...))
}

// GuestAccessExpiryGT applies the GT predicate on the "guest_access_expiry" field.
func GuestAccessExpiryGT(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldGuestAccessExpiry, v))
}

// GuestAccessExpiryGTE applies the GTE predicate on the "guest_access_expiry" field.
func GuestAccessExpiryGTE(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldGuestAccessExpiry, v))
}

// GuestAccessExpiryLT applies the LT predicate on the "guest_access_expiry" field.
func GuestAccessExpiryLT(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldGuestAccessExpiry, v))
}

// GuestAccessExpiryLTE applies the LTE predicate on the "guest_access_expiry" field.
func GuestAccessExpiryLTE(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldGuestAccessExpiry, v))
}

// GuestAccessExpiryIsNil applies the IsNil predicate on the "guest_access_expiry" field.
func GuestAccessExpiryIsNil() predicate.Space {
	return predicate.Space(sql.FieldIsNull(FieldGuestAccessExpiry))
}

// GuestAccessExpiryNotNil applies the NotNil predicate on the "guest_access_expiry" field.
func GuestAccessExpiryNotNil() predicate.Space {
	return predicate.Space(sql.FieldNotNull(FieldGuestAccessExpiry))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Space {
	return predicate.Space(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Space {
	return predicate.Space(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Space {
	return predicate.Space(sql.FieldContainsFold(FieldStatus, v))
}

// ProcessingStatusEQ applies the EQ predicate on the "processing_status" field.
func ProcessingStatusEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldProcessingStatus, v))
}

// ProcessingStatusNEQ applies the NEQ predicate on the "processing_status" field.
func ProcessingStatusNEQ(v string) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldProcessingStatus, v))
}

// ProcessingStatusIn applies the In predicate on the "processing_status" field.
func ProcessingStatusIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldProcessingStatus, vs...))
}

// ProcessingStatusNotIn applies the NotIn predicate on the "processing_status" field.
func ProcessingStatusNotIn(vs ...string) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldProcessingStatus, vs...))
}

// ProcessingStatusGT applies the GT predicate on the "processing_status" field.
func ProcessingStatusGT(v string) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldProcessingStatus, v))
}

// ProcessingStatusGTE applies the GTE predicate on the "processing_status" field.
func ProcessingStatusGTE(v string) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldProcessingStatus, v))
}

// ProcessingStatusLT applies the LT predicate on the "processing_status" field.
func ProcessingStatusLT(v string) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldProcessingStatus, v))
}

// ProcessingStatusLTE applies the LTE predicate on the "processing_status" field.
func ProcessingStatusLTE(v string) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldProcessingStatus, v))
}

// ProcessingStatusContains applies the Contains predicate on the "processing_status" field.
func ProcessingStatusContains(v string) predicate.Space {
	return predicate.Space(sql.FieldContains(FieldProcessingStatus, v))
}

// ProcessingStatusHasPrefix applies the HasPrefix predicate on the "processing_status" field.
func ProcessingStatusHasPrefix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasPrefix(FieldProcessingStatus, v))
}

// ProcessingStatusHasSuffix applies the HasSuffix predicate on the "processing_status" field.
func ProcessingStatusHasSuffix(v string) predicate.Space {
	return predicate.Space(sql.FieldHasSuffix(FieldProcessingStatus, v))
}

// ProcessingStatusEqualFold applies the EqualFold predicate on the "processing_status" field.
func ProcessingStatusEqualFold(v string) predicate.Space {
	return predicate.Space(sql.FieldEqualFold(FieldProcessingStatus, v))
}

// ProcessingStatusContainsFold applies the ContainsFold predicate on the "processing_status" field.
func ProcessingStatusContainsFold(v string) predicate.Space {
	return predicate.Space(sql.FieldContainsFold(FieldProcessingStatus, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Space {
	return predicate.Space(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Space {
	return predicate.Space(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Space {
	return predicate.Space(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Space {
	return predicate.Space(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Space {
	return predicate.Space(sql.FieldNotNull(FieldDeletedAt))
}

// HasContentSources applies the HasEdge predicate on the "content_sources" edge.
func HasContentSources() predicate.Space {
	return predicate.Space(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ContentSourcesTable, ContentSourcesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContentSourcesWith applies the HasEdge predicate on the "content_sources" edge with a given conditions (other predicates).
func HasContentSourcesWith(preds ...predicate.ContentSource) predicate.Space {
	return predicate.Space(func(s *sql.Selector) {
		step := newContentSourcesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Space) predicate.Space {
	return predicate.Space(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Space) predicate.Space {
	return predicate.Space(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Space) predicate.Space {
	return predicate.Space(sql.NotPredicates(p))
}
