// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/public/v1/canvas.proto

package canvaspublicv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CanvasPublic_SemanticSearch_FullMethodName        = "/canvas.public.v1.CanvasPublic/SemanticSearch"
	CanvasPublic_GetNodes_FullMethodName              = "/canvas.public.v1.CanvasPublic/GetNodes"
	CanvasPublic_GetNeighbors_FullMethodName          = "/canvas.public.v1.CanvasPublic/GetNeighbors"
	CanvasPublic_SearchNodes_FullMethodName           = "/canvas.public.v1.CanvasPublic/SearchNodes"
	CanvasPublic_UpdateNodes_FullMethodName           = "/canvas.public.v1.CanvasPublic/UpdateNodes"
	CanvasPublic_GetLinks_FullMethodName              = "/canvas.public.v1.CanvasPublic/GetLinks"
	CanvasPublic_CreateStructuralLinks_FullMethodName = "/canvas.public.v1.CanvasPublic/CreateStructuralLinks"
	CanvasPublic_UpdateStructuralLinks_FullMethodName = "/canvas.public.v1.CanvasPublic/UpdateStructuralLinks"
	CanvasPublic_DeleteStructuralLinks_FullMethodName = "/canvas.public.v1.CanvasPublic/DeleteStructuralLinks"
)

// CanvasPublicClient is the client API for CanvasPublic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Public Canvas API
type CanvasPublicClient interface {
	// Semantic Search
	SemanticSearch(ctx context.Context, in *SemanticSearchRequest, opts ...grpc.CallOption) (*SemanticSearchResponse, error)
	// Nodes (Node Creation and Deletion depends on content source status)
	GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error)
	GetNeighbors(ctx context.Context, in *GetNeighborsRequest, opts ...grpc.CallOption) (*GetNeighborsResponse, error)
	SearchNodes(ctx context.Context, in *SearchNodesRequest, opts ...grpc.CallOption) (*SearchNodesResponse, error)
	UpdateNodes(ctx context.Context, in *UpdateNodesRequest, opts ...grpc.CallOption) (*UpdateNodesResponse, error)
	// Links
	// Gets links based on a batch of queries or by direct IDs.
	GetLinks(ctx context.Context, in *GetLinksRequest, opts ...grpc.CallOption) (*GetLinksResponse, error)
	// Useers can manage structural links
	CreateStructuralLinks(ctx context.Context, in *CreateStructuralLinksRequest, opts ...grpc.CallOption) (*CreateStructuralLinksResponse, error)
	UpdateStructuralLinks(ctx context.Context, in *UpdateStructuralLinksRequest, opts ...grpc.CallOption) (*UpdateStructuralLinksResponse, error)
	DeleteStructuralLinks(ctx context.Context, in *DeleteStructuralLinksRequest, opts ...grpc.CallOption) (*DeleteStructuralLinksResponse, error)
}

type canvasPublicClient struct {
	cc grpc.ClientConnInterface
}

func NewCanvasPublicClient(cc grpc.ClientConnInterface) CanvasPublicClient {
	return &canvasPublicClient{cc}
}

func (c *canvasPublicClient) SemanticSearch(ctx context.Context, in *SemanticSearchRequest, opts ...grpc.CallOption) (*SemanticSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SemanticSearchResponse)
	err := c.cc.Invoke(ctx, CanvasPublic_SemanticSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canvasPublicClient) GetNodes(ctx context.Context, in *GetNodesRequest, opts ...grpc.CallOption) (*GetNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodesResponse)
	err := c.cc.Invoke(ctx, CanvasPublic_GetNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canvasPublicClient) GetNeighbors(ctx context.Context, in *GetNeighborsRequest, opts ...grpc.CallOption) (*GetNeighborsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNeighborsResponse)
	err := c.cc.Invoke(ctx, CanvasPublic_GetNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canvasPublicClient) SearchNodes(ctx context.Context, in *SearchNodesRequest, opts ...grpc.CallOption) (*SearchNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchNodesResponse)
	err := c.cc.Invoke(ctx, CanvasPublic_SearchNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canvasPublicClient) UpdateNodes(ctx context.Context, in *UpdateNodesRequest, opts ...grpc.CallOption) (*UpdateNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNodesResponse)
	err := c.cc.Invoke(ctx, CanvasPublic_UpdateNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canvasPublicClient) GetLinks(ctx context.Context, in *GetLinksRequest, opts ...grpc.CallOption) (*GetLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLinksResponse)
	err := c.cc.Invoke(ctx, CanvasPublic_GetLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canvasPublicClient) CreateStructuralLinks(ctx context.Context, in *CreateStructuralLinksRequest, opts ...grpc.CallOption) (*CreateStructuralLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStructuralLinksResponse)
	err := c.cc.Invoke(ctx, CanvasPublic_CreateStructuralLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canvasPublicClient) UpdateStructuralLinks(ctx context.Context, in *UpdateStructuralLinksRequest, opts ...grpc.CallOption) (*UpdateStructuralLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStructuralLinksResponse)
	err := c.cc.Invoke(ctx, CanvasPublic_UpdateStructuralLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *canvasPublicClient) DeleteStructuralLinks(ctx context.Context, in *DeleteStructuralLinksRequest, opts ...grpc.CallOption) (*DeleteStructuralLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStructuralLinksResponse)
	err := c.cc.Invoke(ctx, CanvasPublic_DeleteStructuralLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CanvasPublicServer is the server API for CanvasPublic service.
// All implementations must embed UnimplementedCanvasPublicServer
// for forward compatibility.
//
// Public Canvas API
type CanvasPublicServer interface {
	// Semantic Search
	SemanticSearch(context.Context, *SemanticSearchRequest) (*SemanticSearchResponse, error)
	// Nodes (Node Creation and Deletion depends on content source status)
	GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error)
	GetNeighbors(context.Context, *GetNeighborsRequest) (*GetNeighborsResponse, error)
	SearchNodes(context.Context, *SearchNodesRequest) (*SearchNodesResponse, error)
	UpdateNodes(context.Context, *UpdateNodesRequest) (*UpdateNodesResponse, error)
	// Links
	// Gets links based on a batch of queries or by direct IDs.
	GetLinks(context.Context, *GetLinksRequest) (*GetLinksResponse, error)
	// Useers can manage structural links
	CreateStructuralLinks(context.Context, *CreateStructuralLinksRequest) (*CreateStructuralLinksResponse, error)
	UpdateStructuralLinks(context.Context, *UpdateStructuralLinksRequest) (*UpdateStructuralLinksResponse, error)
	DeleteStructuralLinks(context.Context, *DeleteStructuralLinksRequest) (*DeleteStructuralLinksResponse, error)
	mustEmbedUnimplementedCanvasPublicServer()
}

// UnimplementedCanvasPublicServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCanvasPublicServer struct{}

func (UnimplementedCanvasPublicServer) SemanticSearch(context.Context, *SemanticSearchRequest) (*SemanticSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SemanticSearch not implemented")
}
func (UnimplementedCanvasPublicServer) GetNodes(context.Context, *GetNodesRequest) (*GetNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedCanvasPublicServer) GetNeighbors(context.Context, *GetNeighborsRequest) (*GetNeighborsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNeighbors not implemented")
}
func (UnimplementedCanvasPublicServer) SearchNodes(context.Context, *SearchNodesRequest) (*SearchNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchNodes not implemented")
}
func (UnimplementedCanvasPublicServer) UpdateNodes(context.Context, *UpdateNodesRequest) (*UpdateNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNodes not implemented")
}
func (UnimplementedCanvasPublicServer) GetLinks(context.Context, *GetLinksRequest) (*GetLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLinks not implemented")
}
func (UnimplementedCanvasPublicServer) CreateStructuralLinks(context.Context, *CreateStructuralLinksRequest) (*CreateStructuralLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStructuralLinks not implemented")
}
func (UnimplementedCanvasPublicServer) UpdateStructuralLinks(context.Context, *UpdateStructuralLinksRequest) (*UpdateStructuralLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStructuralLinks not implemented")
}
func (UnimplementedCanvasPublicServer) DeleteStructuralLinks(context.Context, *DeleteStructuralLinksRequest) (*DeleteStructuralLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStructuralLinks not implemented")
}
func (UnimplementedCanvasPublicServer) mustEmbedUnimplementedCanvasPublicServer() {}
func (UnimplementedCanvasPublicServer) testEmbeddedByValue()                      {}

// UnsafeCanvasPublicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CanvasPublicServer will
// result in compilation errors.
type UnsafeCanvasPublicServer interface {
	mustEmbedUnimplementedCanvasPublicServer()
}

func RegisterCanvasPublicServer(s grpc.ServiceRegistrar, srv CanvasPublicServer) {
	// If the following call pancis, it indicates UnimplementedCanvasPublicServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CanvasPublic_ServiceDesc, srv)
}

func _CanvasPublic_SemanticSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemanticSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanvasPublicServer).SemanticSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanvasPublic_SemanticSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanvasPublicServer).SemanticSearch(ctx, req.(*SemanticSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CanvasPublic_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanvasPublicServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanvasPublic_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanvasPublicServer).GetNodes(ctx, req.(*GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CanvasPublic_GetNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanvasPublicServer).GetNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanvasPublic_GetNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanvasPublicServer).GetNeighbors(ctx, req.(*GetNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CanvasPublic_SearchNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanvasPublicServer).SearchNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanvasPublic_SearchNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanvasPublicServer).SearchNodes(ctx, req.(*SearchNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CanvasPublic_UpdateNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanvasPublicServer).UpdateNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanvasPublic_UpdateNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanvasPublicServer).UpdateNodes(ctx, req.(*UpdateNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CanvasPublic_GetLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanvasPublicServer).GetLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanvasPublic_GetLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanvasPublicServer).GetLinks(ctx, req.(*GetLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CanvasPublic_CreateStructuralLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStructuralLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanvasPublicServer).CreateStructuralLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanvasPublic_CreateStructuralLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanvasPublicServer).CreateStructuralLinks(ctx, req.(*CreateStructuralLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CanvasPublic_UpdateStructuralLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStructuralLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanvasPublicServer).UpdateStructuralLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanvasPublic_UpdateStructuralLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanvasPublicServer).UpdateStructuralLinks(ctx, req.(*UpdateStructuralLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CanvasPublic_DeleteStructuralLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStructuralLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CanvasPublicServer).DeleteStructuralLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CanvasPublic_DeleteStructuralLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CanvasPublicServer).DeleteStructuralLinks(ctx, req.(*DeleteStructuralLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CanvasPublic_ServiceDesc is the grpc.ServiceDesc for CanvasPublic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CanvasPublic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "canvas.public.v1.CanvasPublic",
	HandlerType: (*CanvasPublicServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SemanticSearch",
			Handler:    _CanvasPublic_SemanticSearch_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _CanvasPublic_GetNodes_Handler,
		},
		{
			MethodName: "GetNeighbors",
			Handler:    _CanvasPublic_GetNeighbors_Handler,
		},
		{
			MethodName: "SearchNodes",
			Handler:    _CanvasPublic_SearchNodes_Handler,
		},
		{
			MethodName: "UpdateNodes",
			Handler:    _CanvasPublic_UpdateNodes_Handler,
		},
		{
			MethodName: "GetLinks",
			Handler:    _CanvasPublic_GetLinks_Handler,
		},
		{
			MethodName: "CreateStructuralLinks",
			Handler:    _CanvasPublic_CreateStructuralLinks_Handler,
		},
		{
			MethodName: "UpdateStructuralLinks",
			Handler:    _CanvasPublic_UpdateStructuralLinks_Handler,
		},
		{
			MethodName: "DeleteStructuralLinks",
			Handler:    _CanvasPublic_DeleteStructuralLinks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public/v1/canvas.proto",
}
