// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"demo/ms_knowledge/ent/migrate"

	"demo/ms_knowledge/ent/contentsource"
	"demo/ms_knowledge/ent/space"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// ContentSource is the client for interacting with the ContentSource builders.
	ContentSource *ContentSourceClient
	// Space is the client for interacting with the Space builders.
	Space *SpaceClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.ContentSource = NewContentSourceClient(c.config)
	c.Space = NewSpaceClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		ContentSource: NewContentSourceClient(cfg),
		Space:         NewSpaceClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		ContentSource: NewContentSourceClient(cfg),
		Space:         NewSpaceClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		ContentSource.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.ContentSource.Use(hooks...)
	c.Space.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.ContentSource.Intercept(interceptors...)
	c.Space.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ContentSourceMutation:
		return c.ContentSource.mutate(ctx, m)
	case *SpaceMutation:
		return c.Space.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ContentSourceClient is a client for the ContentSource schema.
type ContentSourceClient struct {
	config
}

// NewContentSourceClient returns a client for the ContentSource from the given config.
func NewContentSourceClient(c config) *ContentSourceClient {
	return &ContentSourceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `contentsource.Hooks(f(g(h())))`.
func (c *ContentSourceClient) Use(hooks ...Hook) {
	c.hooks.ContentSource = append(c.hooks.ContentSource, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `contentsource.Intercept(f(g(h())))`.
func (c *ContentSourceClient) Intercept(interceptors ...Interceptor) {
	c.inters.ContentSource = append(c.inters.ContentSource, interceptors...)
}

// Create returns a builder for creating a ContentSource entity.
func (c *ContentSourceClient) Create() *ContentSourceCreate {
	mutation := newContentSourceMutation(c.config, OpCreate)
	return &ContentSourceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ContentSource entities.
func (c *ContentSourceClient) CreateBulk(builders ...*ContentSourceCreate) *ContentSourceCreateBulk {
	return &ContentSourceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ContentSourceClient) MapCreateBulk(slice any, setFunc func(*ContentSourceCreate, int)) *ContentSourceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ContentSourceCreateBulk{err: fmt.Errorf("calling to ContentSourceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ContentSourceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ContentSourceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ContentSource.
func (c *ContentSourceClient) Update() *ContentSourceUpdate {
	mutation := newContentSourceMutation(c.config, OpUpdate)
	return &ContentSourceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ContentSourceClient) UpdateOne(cs *ContentSource) *ContentSourceUpdateOne {
	mutation := newContentSourceMutation(c.config, OpUpdateOne, withContentSource(cs))
	return &ContentSourceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ContentSourceClient) UpdateOneID(id uuid.UUID) *ContentSourceUpdateOne {
	mutation := newContentSourceMutation(c.config, OpUpdateOne, withContentSourceID(id))
	return &ContentSourceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ContentSource.
func (c *ContentSourceClient) Delete() *ContentSourceDelete {
	mutation := newContentSourceMutation(c.config, OpDelete)
	return &ContentSourceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ContentSourceClient) DeleteOne(cs *ContentSource) *ContentSourceDeleteOne {
	return c.DeleteOneID(cs.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ContentSourceClient) DeleteOneID(id uuid.UUID) *ContentSourceDeleteOne {
	builder := c.Delete().Where(contentsource.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ContentSourceDeleteOne{builder}
}

// Query returns a query builder for ContentSource.
func (c *ContentSourceClient) Query() *ContentSourceQuery {
	return &ContentSourceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeContentSource},
		inters: c.Interceptors(),
	}
}

// Get returns a ContentSource entity by its id.
func (c *ContentSourceClient) Get(ctx context.Context, id uuid.UUID) (*ContentSource, error) {
	return c.Query().Where(contentsource.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ContentSourceClient) GetX(ctx context.Context, id uuid.UUID) *ContentSource {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySpace queries the space edge of a ContentSource.
func (c *ContentSourceClient) QuerySpace(cs *ContentSource) *SpaceQuery {
	query := (&SpaceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := cs.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(contentsource.Table, contentsource.FieldID, id),
			sqlgraph.To(space.Table, space.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, contentsource.SpaceTable, contentsource.SpaceColumn),
		)
		fromV = sqlgraph.Neighbors(cs.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ContentSourceClient) Hooks() []Hook {
	return c.hooks.ContentSource
}

// Interceptors returns the client interceptors.
func (c *ContentSourceClient) Interceptors() []Interceptor {
	return c.inters.ContentSource
}

func (c *ContentSourceClient) mutate(ctx context.Context, m *ContentSourceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ContentSourceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ContentSourceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ContentSourceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ContentSourceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ContentSource mutation op: %q", m.Op())
	}
}

// SpaceClient is a client for the Space schema.
type SpaceClient struct {
	config
}

// NewSpaceClient returns a client for the Space from the given config.
func NewSpaceClient(c config) *SpaceClient {
	return &SpaceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `space.Hooks(f(g(h())))`.
func (c *SpaceClient) Use(hooks ...Hook) {
	c.hooks.Space = append(c.hooks.Space, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `space.Intercept(f(g(h())))`.
func (c *SpaceClient) Intercept(interceptors ...Interceptor) {
	c.inters.Space = append(c.inters.Space, interceptors...)
}

// Create returns a builder for creating a Space entity.
func (c *SpaceClient) Create() *SpaceCreate {
	mutation := newSpaceMutation(c.config, OpCreate)
	return &SpaceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Space entities.
func (c *SpaceClient) CreateBulk(builders ...*SpaceCreate) *SpaceCreateBulk {
	return &SpaceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SpaceClient) MapCreateBulk(slice any, setFunc func(*SpaceCreate, int)) *SpaceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SpaceCreateBulk{err: fmt.Errorf("calling to SpaceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SpaceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SpaceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Space.
func (c *SpaceClient) Update() *SpaceUpdate {
	mutation := newSpaceMutation(c.config, OpUpdate)
	return &SpaceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SpaceClient) UpdateOne(s *Space) *SpaceUpdateOne {
	mutation := newSpaceMutation(c.config, OpUpdateOne, withSpace(s))
	return &SpaceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SpaceClient) UpdateOneID(id uuid.UUID) *SpaceUpdateOne {
	mutation := newSpaceMutation(c.config, OpUpdateOne, withSpaceID(id))
	return &SpaceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Space.
func (c *SpaceClient) Delete() *SpaceDelete {
	mutation := newSpaceMutation(c.config, OpDelete)
	return &SpaceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SpaceClient) DeleteOne(s *Space) *SpaceDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SpaceClient) DeleteOneID(id uuid.UUID) *SpaceDeleteOne {
	builder := c.Delete().Where(space.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SpaceDeleteOne{builder}
}

// Query returns a query builder for Space.
func (c *SpaceClient) Query() *SpaceQuery {
	return &SpaceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSpace},
		inters: c.Interceptors(),
	}
}

// Get returns a Space entity by its id.
func (c *SpaceClient) Get(ctx context.Context, id uuid.UUID) (*Space, error) {
	return c.Query().Where(space.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SpaceClient) GetX(ctx context.Context, id uuid.UUID) *Space {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryContentSources queries the content_sources edge of a Space.
func (c *SpaceClient) QueryContentSources(s *Space) *ContentSourceQuery {
	query := (&ContentSourceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(space.Table, space.FieldID, id),
			sqlgraph.To(contentsource.Table, contentsource.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, space.ContentSourcesTable, space.ContentSourcesColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SpaceClient) Hooks() []Hook {
	return c.hooks.Space
}

// Interceptors returns the client interceptors.
func (c *SpaceClient) Interceptors() []Interceptor {
	return c.inters.Space
}

func (c *SpaceClient) mutate(ctx context.Context, m *SpaceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SpaceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SpaceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SpaceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SpaceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Space mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		ContentSource, Space []ent.Hook
	}
	inters struct {
		ContentSource, Space []ent.Interceptor
	}
)
