// Code generated by ent, DO NOT EDIT.

package ent

import (
	"demo/ms_knowledge/ent/contentsource"
	"demo/ms_knowledge/ent/space"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ContentSource is the model entity for the ContentSource schema.
type ContentSource struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SpaceID holds the value of the "space_id" field.
	SpaceID uuid.UUID `json:"space_id,omitempty"`
	// OwnerID holds the value of the "owner_id" field.
	OwnerID uuid.UUID `json:"owner_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// MediaType holds the value of the "media_type" field.
	MediaType string `json:"media_type,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// OriginalBlobHash holds the value of the "original_blob_hash" field.
	OriginalBlobHash string `json:"original_blob_hash,omitempty"`
	// ProcessedBlobHash holds the value of the "processed_blob_hash" field.
	ProcessedBlobHash *string `json:"processed_blob_hash,omitempty"`
	// ContentSummary holds the value of the "content_summary" field.
	ContentSummary *string `json:"content_summary,omitempty"`
	// Keywords holds the value of the "keywords" field.
	Keywords []string `json:"keywords,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ContentSourceQuery when eager-loading is set.
	Edges        ContentSourceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ContentSourceEdges holds the relations/edges for other nodes in the graph.
type ContentSourceEdges struct {
	// Space holds the value of the space edge.
	Space *Space `json:"space,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SpaceOrErr returns the Space value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ContentSourceEdges) SpaceOrErr() (*Space, error) {
	if e.Space != nil {
		return e.Space, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: space.Label}
	}
	return nil, &NotLoadedError{edge: "space"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContentSource) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contentsource.FieldKeywords:
			values[i] = new([]byte)
		case contentsource.FieldTitle, contentsource.FieldMediaType, contentsource.FieldSource, contentsource.FieldStatus, contentsource.FieldOriginalBlobHash, contentsource.FieldProcessedBlobHash, contentsource.FieldContentSummary:
			values[i] = new(sql.NullString)
		case contentsource.FieldCreatedAt, contentsource.FieldUpdatedAt, contentsource.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case contentsource.FieldID, contentsource.FieldSpaceID, contentsource.FieldOwnerID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContentSource fields.
func (cs *ContentSource) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contentsource.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				cs.ID = *value
			}
		case contentsource.FieldSpaceID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field space_id", values[i])
			} else if value != nil {
				cs.SpaceID = *value
			}
		case contentsource.FieldOwnerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field owner_id", values[i])
			} else if value != nil {
				cs.OwnerID = *value
			}
		case contentsource.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				cs.Title = value.String
			}
		case contentsource.FieldMediaType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field media_type", values[i])
			} else if value.Valid {
				cs.MediaType = value.String
			}
		case contentsource.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				cs.Source = value.String
			}
		case contentsource.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				cs.Status = value.String
			}
		case contentsource.FieldOriginalBlobHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field original_blob_hash", values[i])
			} else if value.Valid {
				cs.OriginalBlobHash = value.String
			}
		case contentsource.FieldProcessedBlobHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field processed_blob_hash", values[i])
			} else if value.Valid {
				cs.ProcessedBlobHash = new(string)
				*cs.ProcessedBlobHash = value.String
			}
		case contentsource.FieldContentSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_summary", values[i])
			} else if value.Valid {
				cs.ContentSummary = new(string)
				*cs.ContentSummary = value.String
			}
		case contentsource.FieldKeywords:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field keywords", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &cs.Keywords); err != nil {
					return fmt.Errorf("unmarshal field keywords: %w", err)
				}
			}
		case contentsource.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				cs.CreatedAt = value.Time
			}
		case contentsource.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				cs.UpdatedAt = value.Time
			}
		case contentsource.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				cs.DeletedAt = new(time.Time)
				*cs.DeletedAt = value.Time
			}
		default:
			cs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContentSource.
// This includes values selected through modifiers, order, etc.
func (cs *ContentSource) Value(name string) (ent.Value, error) {
	return cs.selectValues.Get(name)
}

// QuerySpace queries the "space" edge of the ContentSource entity.
func (cs *ContentSource) QuerySpace() *SpaceQuery {
	return NewContentSourceClient(cs.config).QuerySpace(cs)
}

// Update returns a builder for updating this ContentSource.
// Note that you need to call ContentSource.Unwrap() before calling this method if this ContentSource
// was returned from a transaction, and the transaction was committed or rolled back.
func (cs *ContentSource) Update() *ContentSourceUpdateOne {
	return NewContentSourceClient(cs.config).UpdateOne(cs)
}

// Unwrap unwraps the ContentSource entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cs *ContentSource) Unwrap() *ContentSource {
	_tx, ok := cs.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContentSource is not a transactional entity")
	}
	cs.config.driver = _tx.drv
	return cs
}

// String implements the fmt.Stringer.
func (cs *ContentSource) String() string {
	var builder strings.Builder
	builder.WriteString("ContentSource(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cs.ID))
	builder.WriteString("space_id=")
	builder.WriteString(fmt.Sprintf("%v", cs.SpaceID))
	builder.WriteString(", ")
	builder.WriteString("owner_id=")
	builder.WriteString(fmt.Sprintf("%v", cs.OwnerID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(cs.Title)
	builder.WriteString(", ")
	builder.WriteString("media_type=")
	builder.WriteString(cs.MediaType)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(cs.Source)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(cs.Status)
	builder.WriteString(", ")
	builder.WriteString("original_blob_hash=")
	builder.WriteString(cs.OriginalBlobHash)
	builder.WriteString(", ")
	if v := cs.ProcessedBlobHash; v != nil {
		builder.WriteString("processed_blob_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := cs.ContentSummary; v != nil {
		builder.WriteString("content_summary=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("keywords=")
	builder.WriteString(fmt.Sprintf("%v", cs.Keywords))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(cs.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(cs.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := cs.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ContentSources is a parsable slice of ContentSource.
type ContentSources []*ContentSource
