// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"demo/ms_knowledge/ent/contentsource"
	"demo/ms_knowledge/ent/space"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ContentSourceCreate is the builder for creating a ContentSource entity.
type ContentSourceCreate struct {
	config
	mutation *ContentSourceMutation
	hooks    []Hook
}

// SetSpaceID sets the "space_id" field.
func (csc *ContentSourceCreate) SetSpaceID(u uuid.UUID) *ContentSourceCreate {
	csc.mutation.SetSpaceID(u)
	return csc
}

// SetOwnerID sets the "owner_id" field.
func (csc *ContentSourceCreate) SetOwnerID(u uuid.UUID) *ContentSourceCreate {
	csc.mutation.SetOwnerID(u)
	return csc
}

// SetTitle sets the "title" field.
func (csc *ContentSourceCreate) SetTitle(s string) *ContentSourceCreate {
	csc.mutation.SetTitle(s)
	return csc
}

// SetMediaType sets the "media_type" field.
func (csc *ContentSourceCreate) SetMediaType(s string) *ContentSourceCreate {
	csc.mutation.SetMediaType(s)
	return csc
}

// SetSource sets the "source" field.
func (csc *ContentSourceCreate) SetSource(s string) *ContentSourceCreate {
	csc.mutation.SetSource(s)
	return csc
}

// SetStatus sets the "status" field.
func (csc *ContentSourceCreate) SetStatus(s string) *ContentSourceCreate {
	csc.mutation.SetStatus(s)
	return csc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (csc *ContentSourceCreate) SetNillableStatus(s *string) *ContentSourceCreate {
	if s != nil {
		csc.SetStatus(*s)
	}
	return csc
}

// SetOriginalBlobHash sets the "original_blob_hash" field.
func (csc *ContentSourceCreate) SetOriginalBlobHash(s string) *ContentSourceCreate {
	csc.mutation.SetOriginalBlobHash(s)
	return csc
}

// SetProcessedBlobHash sets the "processed_blob_hash" field.
func (csc *ContentSourceCreate) SetProcessedBlobHash(s string) *ContentSourceCreate {
	csc.mutation.SetProcessedBlobHash(s)
	return csc
}

// SetNillableProcessedBlobHash sets the "processed_blob_hash" field if the given value is not nil.
func (csc *ContentSourceCreate) SetNillableProcessedBlobHash(s *string) *ContentSourceCreate {
	if s != nil {
		csc.SetProcessedBlobHash(*s)
	}
	return csc
}

// SetContentSummary sets the "content_summary" field.
func (csc *ContentSourceCreate) SetContentSummary(s string) *ContentSourceCreate {
	csc.mutation.SetContentSummary(s)
	return csc
}

// SetNillableContentSummary sets the "content_summary" field if the given value is not nil.
func (csc *ContentSourceCreate) SetNillableContentSummary(s *string) *ContentSourceCreate {
	if s != nil {
		csc.SetContentSummary(*s)
	}
	return csc
}

// SetKeywords sets the "keywords" field.
func (csc *ContentSourceCreate) SetKeywords(s []string) *ContentSourceCreate {
	csc.mutation.SetKeywords(s)
	return csc
}

// SetCreatedAt sets the "created_at" field.
func (csc *ContentSourceCreate) SetCreatedAt(t time.Time) *ContentSourceCreate {
	csc.mutation.SetCreatedAt(t)
	return csc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (csc *ContentSourceCreate) SetNillableCreatedAt(t *time.Time) *ContentSourceCreate {
	if t != nil {
		csc.SetCreatedAt(*t)
	}
	return csc
}

// SetUpdatedAt sets the "updated_at" field.
func (csc *ContentSourceCreate) SetUpdatedAt(t time.Time) *ContentSourceCreate {
	csc.mutation.SetUpdatedAt(t)
	return csc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (csc *ContentSourceCreate) SetNillableUpdatedAt(t *time.Time) *ContentSourceCreate {
	if t != nil {
		csc.SetUpdatedAt(*t)
	}
	return csc
}

// SetDeletedAt sets the "deleted_at" field.
func (csc *ContentSourceCreate) SetDeletedAt(t time.Time) *ContentSourceCreate {
	csc.mutation.SetDeletedAt(t)
	return csc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (csc *ContentSourceCreate) SetNillableDeletedAt(t *time.Time) *ContentSourceCreate {
	if t != nil {
		csc.SetDeletedAt(*t)
	}
	return csc
}

// SetID sets the "id" field.
func (csc *ContentSourceCreate) SetID(u uuid.UUID) *ContentSourceCreate {
	csc.mutation.SetID(u)
	return csc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (csc *ContentSourceCreate) SetNillableID(u *uuid.UUID) *ContentSourceCreate {
	if u != nil {
		csc.SetID(*u)
	}
	return csc
}

// SetSpace sets the "space" edge to the Space entity.
func (csc *ContentSourceCreate) SetSpace(s *Space) *ContentSourceCreate {
	return csc.SetSpaceID(s.ID)
}

// Mutation returns the ContentSourceMutation object of the builder.
func (csc *ContentSourceCreate) Mutation() *ContentSourceMutation {
	return csc.mutation
}

// Save creates the ContentSource in the database.
func (csc *ContentSourceCreate) Save(ctx context.Context) (*ContentSource, error) {
	csc.defaults()
	return withHooks(ctx, csc.sqlSave, csc.mutation, csc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (csc *ContentSourceCreate) SaveX(ctx context.Context) *ContentSource {
	v, err := csc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (csc *ContentSourceCreate) Exec(ctx context.Context) error {
	_, err := csc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csc *ContentSourceCreate) ExecX(ctx context.Context) {
	if err := csc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (csc *ContentSourceCreate) defaults() {
	if _, ok := csc.mutation.Status(); !ok {
		v := contentsource.DefaultStatus
		csc.mutation.SetStatus(v)
	}
	if _, ok := csc.mutation.CreatedAt(); !ok {
		v := contentsource.DefaultCreatedAt()
		csc.mutation.SetCreatedAt(v)
	}
	if _, ok := csc.mutation.UpdatedAt(); !ok {
		v := contentsource.DefaultUpdatedAt()
		csc.mutation.SetUpdatedAt(v)
	}
	if _, ok := csc.mutation.ID(); !ok {
		v := contentsource.DefaultID()
		csc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (csc *ContentSourceCreate) check() error {
	if _, ok := csc.mutation.SpaceID(); !ok {
		return &ValidationError{Name: "space_id", err: errors.New(`ent: missing required field "ContentSource.space_id"`)}
	}
	if _, ok := csc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "ContentSource.owner_id"`)}
	}
	if _, ok := csc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ContentSource.title"`)}
	}
	if _, ok := csc.mutation.MediaType(); !ok {
		return &ValidationError{Name: "media_type", err: errors.New(`ent: missing required field "ContentSource.media_type"`)}
	}
	if _, ok := csc.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "ContentSource.source"`)}
	}
	if _, ok := csc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ContentSource.status"`)}
	}
	if _, ok := csc.mutation.OriginalBlobHash(); !ok {
		return &ValidationError{Name: "original_blob_hash", err: errors.New(`ent: missing required field "ContentSource.original_blob_hash"`)}
	}
	if v, ok := csc.mutation.OriginalBlobHash(); ok {
		if err := contentsource.OriginalBlobHashValidator(v); err != nil {
			return &ValidationError{Name: "original_blob_hash", err: fmt.Errorf(`ent: validator failed for field "ContentSource.original_blob_hash": %w`, err)}
		}
	}
	if v, ok := csc.mutation.ProcessedBlobHash(); ok {
		if err := contentsource.ProcessedBlobHashValidator(v); err != nil {
			return &ValidationError{Name: "processed_blob_hash", err: fmt.Errorf(`ent: validator failed for field "ContentSource.processed_blob_hash": %w`, err)}
		}
	}
	if _, ok := csc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ContentSource.created_at"`)}
	}
	if _, ok := csc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ContentSource.updated_at"`)}
	}
	if len(csc.mutation.SpaceIDs()) == 0 {
		return &ValidationError{Name: "space", err: errors.New(`ent: missing required edge "ContentSource.space"`)}
	}
	return nil
}

func (csc *ContentSourceCreate) sqlSave(ctx context.Context) (*ContentSource, error) {
	if err := csc.check(); err != nil {
		return nil, err
	}
	_node, _spec := csc.createSpec()
	if err := sqlgraph.CreateNode(ctx, csc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	csc.mutation.id = &_node.ID
	csc.mutation.done = true
	return _node, nil
}

func (csc *ContentSourceCreate) createSpec() (*ContentSource, *sqlgraph.CreateSpec) {
	var (
		_node = &ContentSource{config: csc.config}
		_spec = sqlgraph.NewCreateSpec(contentsource.Table, sqlgraph.NewFieldSpec(contentsource.FieldID, field.TypeUUID))
	)
	if id, ok := csc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := csc.mutation.OwnerID(); ok {
		_spec.SetField(contentsource.FieldOwnerID, field.TypeUUID, value)
		_node.OwnerID = value
	}
	if value, ok := csc.mutation.Title(); ok {
		_spec.SetField(contentsource.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := csc.mutation.MediaType(); ok {
		_spec.SetField(contentsource.FieldMediaType, field.TypeString, value)
		_node.MediaType = value
	}
	if value, ok := csc.mutation.Source(); ok {
		_spec.SetField(contentsource.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := csc.mutation.Status(); ok {
		_spec.SetField(contentsource.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := csc.mutation.OriginalBlobHash(); ok {
		_spec.SetField(contentsource.FieldOriginalBlobHash, field.TypeString, value)
		_node.OriginalBlobHash = value
	}
	if value, ok := csc.mutation.ProcessedBlobHash(); ok {
		_spec.SetField(contentsource.FieldProcessedBlobHash, field.TypeString, value)
		_node.ProcessedBlobHash = &value
	}
	if value, ok := csc.mutation.ContentSummary(); ok {
		_spec.SetField(contentsource.FieldContentSummary, field.TypeString, value)
		_node.ContentSummary = &value
	}
	if value, ok := csc.mutation.Keywords(); ok {
		_spec.SetField(contentsource.FieldKeywords, field.TypeJSON, value)
		_node.Keywords = value
	}
	if value, ok := csc.mutation.CreatedAt(); ok {
		_spec.SetField(contentsource.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := csc.mutation.UpdatedAt(); ok {
		_spec.SetField(contentsource.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := csc.mutation.DeletedAt(); ok {
		_spec.SetField(contentsource.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := csc.mutation.SpaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contentsource.SpaceTable,
			Columns: []string{contentsource.SpaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(space.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SpaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ContentSourceCreateBulk is the builder for creating many ContentSource entities in bulk.
type ContentSourceCreateBulk struct {
	config
	err      error
	builders []*ContentSourceCreate
}

// Save creates the ContentSource entities in the database.
func (cscb *ContentSourceCreateBulk) Save(ctx context.Context) ([]*ContentSource, error) {
	if cscb.err != nil {
		return nil, cscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cscb.builders))
	nodes := make([]*ContentSource, len(cscb.builders))
	mutators := make([]Mutator, len(cscb.builders))
	for i := range cscb.builders {
		func(i int, root context.Context) {
			builder := cscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContentSourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cscb *ContentSourceCreateBulk) SaveX(ctx context.Context) []*ContentSource {
	v, err := cscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cscb *ContentSourceCreateBulk) Exec(ctx context.Context) error {
	_, err := cscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cscb *ContentSourceCreateBulk) ExecX(ctx context.Context) {
	if err := cscb.Exec(ctx); err != nil {
		panic(err)
	}
}
