// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"demo/ms_knowledge/ent/contentsource"
	"demo/ms_knowledge/ent/predicate"
	"demo/ms_knowledge/ent/space"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ContentSourceQuery is the builder for querying ContentSource entities.
type ContentSourceQuery struct {
	config
	ctx        *QueryContext
	order      []contentsource.OrderOption
	inters     []Interceptor
	predicates []predicate.ContentSource
	withSpace  *SpaceQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ContentSourceQuery builder.
func (csq *ContentSourceQuery) Where(ps ...predicate.ContentSource) *ContentSourceQuery {
	csq.predicates = append(csq.predicates, ps...)
	return csq
}

// Limit the number of records to be returned by this query.
func (csq *ContentSourceQuery) Limit(limit int) *ContentSourceQuery {
	csq.ctx.Limit = &limit
	return csq
}

// Offset to start from.
func (csq *ContentSourceQuery) Offset(offset int) *ContentSourceQuery {
	csq.ctx.Offset = &offset
	return csq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (csq *ContentSourceQuery) Unique(unique bool) *ContentSourceQuery {
	csq.ctx.Unique = &unique
	return csq
}

// Order specifies how the records should be ordered.
func (csq *ContentSourceQuery) Order(o ...contentsource.OrderOption) *ContentSourceQuery {
	csq.order = append(csq.order, o...)
	return csq
}

// QuerySpace chains the current query on the "space" edge.
func (csq *ContentSourceQuery) QuerySpace() *SpaceQuery {
	query := (&SpaceClient{config: csq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := csq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := csq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contentsource.Table, contentsource.FieldID, selector),
			sqlgraph.To(space.Table, space.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, contentsource.SpaceTable, contentsource.SpaceColumn),
		)
		fromU = sqlgraph.SetNeighbors(csq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ContentSource entity from the query.
// Returns a *NotFoundError when no ContentSource was found.
func (csq *ContentSourceQuery) First(ctx context.Context) (*ContentSource, error) {
	nodes, err := csq.Limit(1).All(setContextOp(ctx, csq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{contentsource.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (csq *ContentSourceQuery) FirstX(ctx context.Context) *ContentSource {
	node, err := csq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ContentSource ID from the query.
// Returns a *NotFoundError when no ContentSource ID was found.
func (csq *ContentSourceQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = csq.Limit(1).IDs(setContextOp(ctx, csq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{contentsource.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (csq *ContentSourceQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := csq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ContentSource entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ContentSource entity is found.
// Returns a *NotFoundError when no ContentSource entities are found.
func (csq *ContentSourceQuery) Only(ctx context.Context) (*ContentSource, error) {
	nodes, err := csq.Limit(2).All(setContextOp(ctx, csq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{contentsource.Label}
	default:
		return nil, &NotSingularError{contentsource.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (csq *ContentSourceQuery) OnlyX(ctx context.Context) *ContentSource {
	node, err := csq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ContentSource ID in the query.
// Returns a *NotSingularError when more than one ContentSource ID is found.
// Returns a *NotFoundError when no entities are found.
func (csq *ContentSourceQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = csq.Limit(2).IDs(setContextOp(ctx, csq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{contentsource.Label}
	default:
		err = &NotSingularError{contentsource.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (csq *ContentSourceQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := csq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ContentSources.
func (csq *ContentSourceQuery) All(ctx context.Context) ([]*ContentSource, error) {
	ctx = setContextOp(ctx, csq.ctx, ent.OpQueryAll)
	if err := csq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ContentSource, *ContentSourceQuery]()
	return withInterceptors[[]*ContentSource](ctx, csq, qr, csq.inters)
}

// AllX is like All, but panics if an error occurs.
func (csq *ContentSourceQuery) AllX(ctx context.Context) []*ContentSource {
	nodes, err := csq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ContentSource IDs.
func (csq *ContentSourceQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if csq.ctx.Unique == nil && csq.path != nil {
		csq.Unique(true)
	}
	ctx = setContextOp(ctx, csq.ctx, ent.OpQueryIDs)
	if err = csq.Select(contentsource.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (csq *ContentSourceQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := csq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (csq *ContentSourceQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, csq.ctx, ent.OpQueryCount)
	if err := csq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, csq, querierCount[*ContentSourceQuery](), csq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (csq *ContentSourceQuery) CountX(ctx context.Context) int {
	count, err := csq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (csq *ContentSourceQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, csq.ctx, ent.OpQueryExist)
	switch _, err := csq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (csq *ContentSourceQuery) ExistX(ctx context.Context) bool {
	exist, err := csq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ContentSourceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (csq *ContentSourceQuery) Clone() *ContentSourceQuery {
	if csq == nil {
		return nil
	}
	return &ContentSourceQuery{
		config:     csq.config,
		ctx:        csq.ctx.Clone(),
		order:      append([]contentsource.OrderOption{}, csq.order...),
		inters:     append([]Interceptor{}, csq.inters...),
		predicates: append([]predicate.ContentSource{}, csq.predicates...),
		withSpace:  csq.withSpace.Clone(),
		// clone intermediate query.
		sql:  csq.sql.Clone(),
		path: csq.path,
	}
}

// WithSpace tells the query-builder to eager-load the nodes that are connected to
// the "space" edge. The optional arguments are used to configure the query builder of the edge.
func (csq *ContentSourceQuery) WithSpace(opts ...func(*SpaceQuery)) *ContentSourceQuery {
	query := (&SpaceClient{config: csq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	csq.withSpace = query
	return csq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		SpaceID uuid.UUID `json:"space_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ContentSource.Query().
//		GroupBy(contentsource.FieldSpaceID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (csq *ContentSourceQuery) GroupBy(field string, fields ...string) *ContentSourceGroupBy {
	csq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ContentSourceGroupBy{build: csq}
	grbuild.flds = &csq.ctx.Fields
	grbuild.label = contentsource.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		SpaceID uuid.UUID `json:"space_id,omitempty"`
//	}
//
//	client.ContentSource.Query().
//		Select(contentsource.FieldSpaceID).
//		Scan(ctx, &v)
func (csq *ContentSourceQuery) Select(fields ...string) *ContentSourceSelect {
	csq.ctx.Fields = append(csq.ctx.Fields, fields...)
	sbuild := &ContentSourceSelect{ContentSourceQuery: csq}
	sbuild.label = contentsource.Label
	sbuild.flds, sbuild.scan = &csq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ContentSourceSelect configured with the given aggregations.
func (csq *ContentSourceQuery) Aggregate(fns ...AggregateFunc) *ContentSourceSelect {
	return csq.Select().Aggregate(fns...)
}

func (csq *ContentSourceQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range csq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, csq); err != nil {
				return err
			}
		}
	}
	for _, f := range csq.ctx.Fields {
		if !contentsource.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if csq.path != nil {
		prev, err := csq.path(ctx)
		if err != nil {
			return err
		}
		csq.sql = prev
	}
	return nil
}

func (csq *ContentSourceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ContentSource, error) {
	var (
		nodes       = []*ContentSource{}
		_spec       = csq.querySpec()
		loadedTypes = [1]bool{
			csq.withSpace != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ContentSource).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ContentSource{config: csq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, csq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := csq.withSpace; query != nil {
		if err := csq.loadSpace(ctx, query, nodes, nil,
			func(n *ContentSource, e *Space) { n.Edges.Space = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (csq *ContentSourceQuery) loadSpace(ctx context.Context, query *SpaceQuery, nodes []*ContentSource, init func(*ContentSource), assign func(*ContentSource, *Space)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ContentSource)
	for i := range nodes {
		fk := nodes[i].SpaceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(space.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "space_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (csq *ContentSourceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := csq.querySpec()
	_spec.Node.Columns = csq.ctx.Fields
	if len(csq.ctx.Fields) > 0 {
		_spec.Unique = csq.ctx.Unique != nil && *csq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, csq.driver, _spec)
}

func (csq *ContentSourceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(contentsource.Table, contentsource.Columns, sqlgraph.NewFieldSpec(contentsource.FieldID, field.TypeUUID))
	_spec.From = csq.sql
	if unique := csq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if csq.path != nil {
		_spec.Unique = true
	}
	if fields := csq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contentsource.FieldID)
		for i := range fields {
			if fields[i] != contentsource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if csq.withSpace != nil {
			_spec.Node.AddColumnOnce(contentsource.FieldSpaceID)
		}
	}
	if ps := csq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := csq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := csq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := csq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (csq *ContentSourceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(csq.driver.Dialect())
	t1 := builder.Table(contentsource.Table)
	columns := csq.ctx.Fields
	if len(columns) == 0 {
		columns = contentsource.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if csq.sql != nil {
		selector = csq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if csq.ctx.Unique != nil && *csq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range csq.predicates {
		p(selector)
	}
	for _, p := range csq.order {
		p(selector)
	}
	if offset := csq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := csq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ContentSourceGroupBy is the group-by builder for ContentSource entities.
type ContentSourceGroupBy struct {
	selector
	build *ContentSourceQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (csgb *ContentSourceGroupBy) Aggregate(fns ...AggregateFunc) *ContentSourceGroupBy {
	csgb.fns = append(csgb.fns, fns...)
	return csgb
}

// Scan applies the selector query and scans the result into the given value.
func (csgb *ContentSourceGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, csgb.build.ctx, ent.OpQueryGroupBy)
	if err := csgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContentSourceQuery, *ContentSourceGroupBy](ctx, csgb.build, csgb, csgb.build.inters, v)
}

func (csgb *ContentSourceGroupBy) sqlScan(ctx context.Context, root *ContentSourceQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(csgb.fns))
	for _, fn := range csgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*csgb.flds)+len(csgb.fns))
		for _, f := range *csgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*csgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := csgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ContentSourceSelect is the builder for selecting fields of ContentSource entities.
type ContentSourceSelect struct {
	*ContentSourceQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (css *ContentSourceSelect) Aggregate(fns ...AggregateFunc) *ContentSourceSelect {
	css.fns = append(css.fns, fns...)
	return css
}

// Scan applies the selector query and scans the result into the given value.
func (css *ContentSourceSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, css.ctx, ent.OpQuerySelect)
	if err := css.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContentSourceQuery, *ContentSourceSelect](ctx, css.ContentSourceQuery, css, css.inters, v)
}

func (css *ContentSourceSelect) sqlScan(ctx context.Context, root *ContentSourceQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(css.fns))
	for _, fn := range css.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*css.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := css.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
