// Code generated by ent, DO NOT EDIT.

package ent

import (
	"demo/ms_knowledge/ent/contentsource"
	"demo/ms_knowledge/ent/schema"
	"demo/ms_knowledge/ent/space"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	contentsourceFields := schema.ContentSource{}.Fields()
	_ = contentsourceFields
	// contentsourceDescStatus is the schema descriptor for status field.
	contentsourceDescStatus := contentsourceFields[6].Descriptor()
	// contentsource.DefaultStatus holds the default value on creation for the status field.
	contentsource.DefaultStatus = contentsourceDescStatus.Default.(string)
	// contentsourceDescOriginalBlobHash is the schema descriptor for original_blob_hash field.
	contentsourceDescOriginalBlobHash := contentsourceFields[7].Descriptor()
	// contentsource.OriginalBlobHashValidator is a validator for the "original_blob_hash" field. It is called by the builders before save.
	contentsource.OriginalBlobHashValidator = contentsourceDescOriginalBlobHash.Validators[0].(func(string) error)
	// contentsourceDescProcessedBlobHash is the schema descriptor for processed_blob_hash field.
	contentsourceDescProcessedBlobHash := contentsourceFields[8].Descriptor()
	// contentsource.ProcessedBlobHashValidator is a validator for the "processed_blob_hash" field. It is called by the builders before save.
	contentsource.ProcessedBlobHashValidator = contentsourceDescProcessedBlobHash.Validators[0].(func(string) error)
	// contentsourceDescCreatedAt is the schema descriptor for created_at field.
	contentsourceDescCreatedAt := contentsourceFields[11].Descriptor()
	// contentsource.DefaultCreatedAt holds the default value on creation for the created_at field.
	contentsource.DefaultCreatedAt = contentsourceDescCreatedAt.Default.(func() time.Time)
	// contentsourceDescUpdatedAt is the schema descriptor for updated_at field.
	contentsourceDescUpdatedAt := contentsourceFields[12].Descriptor()
	// contentsource.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	contentsource.DefaultUpdatedAt = contentsourceDescUpdatedAt.Default.(func() time.Time)
	// contentsource.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	contentsource.UpdateDefaultUpdatedAt = contentsourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// contentsourceDescID is the schema descriptor for id field.
	contentsourceDescID := contentsourceFields[0].Descriptor()
	// contentsource.DefaultID holds the default value on creation for the id field.
	contentsource.DefaultID = contentsourceDescID.Default.(func() uuid.UUID)
	spaceFields := schema.Space{}.Fields()
	_ = spaceFields
	// spaceDescCreatedAt is the schema descriptor for created_at field.
	spaceDescCreatedAt := spaceFields[7].Descriptor()
	// space.DefaultCreatedAt holds the default value on creation for the created_at field.
	space.DefaultCreatedAt = spaceDescCreatedAt.Default.(func() time.Time)
	// spaceDescLastUpdatedAt is the schema descriptor for last_updated_at field.
	spaceDescLastUpdatedAt := spaceFields[9].Descriptor()
	// space.DefaultLastUpdatedAt holds the default value on creation for the last_updated_at field.
	space.DefaultLastUpdatedAt = spaceDescLastUpdatedAt.Default.(func() time.Time)
	// space.UpdateDefaultLastUpdatedAt holds the default value on update for the last_updated_at field.
	space.UpdateDefaultLastUpdatedAt = spaceDescLastUpdatedAt.UpdateDefault.(func() time.Time)
	// spaceDescDocumentCount is the schema descriptor for document_count field.
	spaceDescDocumentCount := spaceFields[11].Descriptor()
	// space.DefaultDocumentCount holds the default value on creation for the document_count field.
	space.DefaultDocumentCount = spaceDescDocumentCount.Default.(int)
	// spaceDescTotalSizeBytes is the schema descriptor for total_size_bytes field.
	spaceDescTotalSizeBytes := spaceFields[12].Descriptor()
	// space.DefaultTotalSizeBytes holds the default value on creation for the total_size_bytes field.
	space.DefaultTotalSizeBytes = spaceDescTotalSizeBytes.Default.(int64)
	// spaceDescStorageQuotaBytes is the schema descriptor for storage_quota_bytes field.
	spaceDescStorageQuotaBytes := spaceFields[13].Descriptor()
	// space.DefaultStorageQuotaBytes holds the default value on creation for the storage_quota_bytes field.
	space.DefaultStorageQuotaBytes = spaceDescStorageQuotaBytes.Default.(int64)
	// spaceDescAccessLevel is the schema descriptor for access_level field.
	spaceDescAccessLevel := spaceFields[14].Descriptor()
	// space.DefaultAccessLevel holds the default value on creation for the access_level field.
	space.DefaultAccessLevel = spaceDescAccessLevel.Default.(string)
	// spaceDescGuestAccessEnabled is the schema descriptor for guest_access_enabled field.
	spaceDescGuestAccessEnabled := spaceFields[15].Descriptor()
	// space.DefaultGuestAccessEnabled holds the default value on creation for the guest_access_enabled field.
	space.DefaultGuestAccessEnabled = spaceDescGuestAccessEnabled.Default.(bool)
	// spaceDescStatus is the schema descriptor for status field.
	spaceDescStatus := spaceFields[17].Descriptor()
	// space.DefaultStatus holds the default value on creation for the status field.
	space.DefaultStatus = spaceDescStatus.Default.(string)
	// spaceDescProcessingStatus is the schema descriptor for processing_status field.
	spaceDescProcessingStatus := spaceFields[18].Descriptor()
	// space.DefaultProcessingStatus holds the default value on creation for the processing_status field.
	space.DefaultProcessingStatus = spaceDescProcessingStatus.Default.(string)
	// spaceDescID is the schema descriptor for id field.
	spaceDescID := spaceFields[0].Descriptor()
	// space.DefaultID holds the default value on creation for the id field.
	space.DefaultID = spaceDescID.Default.(func() uuid.UUID)
}
