// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"demo/ms_user/ent/predicate"
	"demo/ms_user/ent/user"
	"demo/ms_user/ent/userpreferences"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserPreferencesQuery is the builder for querying UserPreferences entities.
type UserPreferencesQuery struct {
	config
	ctx        *QueryContext
	order      []userpreferences.OrderOption
	inters     []Interceptor
	predicates []predicate.UserPreferences
	withUser   *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserPreferencesQuery builder.
func (upq *UserPreferencesQuery) Where(ps ...predicate.UserPreferences) *UserPreferencesQuery {
	upq.predicates = append(upq.predicates, ps...)
	return upq
}

// Limit the number of records to be returned by this query.
func (upq *UserPreferencesQuery) Limit(limit int) *UserPreferencesQuery {
	upq.ctx.Limit = &limit
	return upq
}

// Offset to start from.
func (upq *UserPreferencesQuery) Offset(offset int) *UserPreferencesQuery {
	upq.ctx.Offset = &offset
	return upq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (upq *UserPreferencesQuery) Unique(unique bool) *UserPreferencesQuery {
	upq.ctx.Unique = &unique
	return upq
}

// Order specifies how the records should be ordered.
func (upq *UserPreferencesQuery) Order(o ...userpreferences.OrderOption) *UserPreferencesQuery {
	upq.order = append(upq.order, o...)
	return upq
}

// QueryUser chains the current query on the "user" edge.
func (upq *UserPreferencesQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: upq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := upq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := upq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(userpreferences.Table, userpreferences.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, userpreferences.UserTable, userpreferences.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(upq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserPreferences entity from the query.
// Returns a *NotFoundError when no UserPreferences was found.
func (upq *UserPreferencesQuery) First(ctx context.Context) (*UserPreferences, error) {
	nodes, err := upq.Limit(1).All(setContextOp(ctx, upq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userpreferences.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (upq *UserPreferencesQuery) FirstX(ctx context.Context) *UserPreferences {
	node, err := upq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserPreferences ID from the query.
// Returns a *NotFoundError when no UserPreferences ID was found.
func (upq *UserPreferencesQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = upq.Limit(1).IDs(setContextOp(ctx, upq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userpreferences.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (upq *UserPreferencesQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := upq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserPreferences entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserPreferences entity is found.
// Returns a *NotFoundError when no UserPreferences entities are found.
func (upq *UserPreferencesQuery) Only(ctx context.Context) (*UserPreferences, error) {
	nodes, err := upq.Limit(2).All(setContextOp(ctx, upq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userpreferences.Label}
	default:
		return nil, &NotSingularError{userpreferences.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (upq *UserPreferencesQuery) OnlyX(ctx context.Context) *UserPreferences {
	node, err := upq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserPreferences ID in the query.
// Returns a *NotSingularError when more than one UserPreferences ID is found.
// Returns a *NotFoundError when no entities are found.
func (upq *UserPreferencesQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = upq.Limit(2).IDs(setContextOp(ctx, upq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userpreferences.Label}
	default:
		err = &NotSingularError{userpreferences.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (upq *UserPreferencesQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := upq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserPreferencesSlice.
func (upq *UserPreferencesQuery) All(ctx context.Context) ([]*UserPreferences, error) {
	ctx = setContextOp(ctx, upq.ctx, ent.OpQueryAll)
	if err := upq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserPreferences, *UserPreferencesQuery]()
	return withInterceptors[[]*UserPreferences](ctx, upq, qr, upq.inters)
}

// AllX is like All, but panics if an error occurs.
func (upq *UserPreferencesQuery) AllX(ctx context.Context) []*UserPreferences {
	nodes, err := upq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserPreferences IDs.
func (upq *UserPreferencesQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if upq.ctx.Unique == nil && upq.path != nil {
		upq.Unique(true)
	}
	ctx = setContextOp(ctx, upq.ctx, ent.OpQueryIDs)
	if err = upq.Select(userpreferences.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (upq *UserPreferencesQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := upq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (upq *UserPreferencesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, upq.ctx, ent.OpQueryCount)
	if err := upq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, upq, querierCount[*UserPreferencesQuery](), upq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (upq *UserPreferencesQuery) CountX(ctx context.Context) int {
	count, err := upq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (upq *UserPreferencesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, upq.ctx, ent.OpQueryExist)
	switch _, err := upq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (upq *UserPreferencesQuery) ExistX(ctx context.Context) bool {
	exist, err := upq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserPreferencesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (upq *UserPreferencesQuery) Clone() *UserPreferencesQuery {
	if upq == nil {
		return nil
	}
	return &UserPreferencesQuery{
		config:     upq.config,
		ctx:        upq.ctx.Clone(),
		order:      append([]userpreferences.OrderOption{}, upq.order...),
		inters:     append([]Interceptor{}, upq.inters...),
		predicates: append([]predicate.UserPreferences{}, upq.predicates...),
		withUser:   upq.withUser.Clone(),
		// clone intermediate query.
		sql:  upq.sql.Clone(),
		path: upq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (upq *UserPreferencesQuery) WithUser(opts ...func(*UserQuery)) *UserPreferencesQuery {
	query := (&UserClient{config: upq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	upq.withUser = query
	return upq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Theme string `json:"theme,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserPreferences.Query().
//		GroupBy(userpreferences.FieldTheme).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (upq *UserPreferencesQuery) GroupBy(field string, fields ...string) *UserPreferencesGroupBy {
	upq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserPreferencesGroupBy{build: upq}
	grbuild.flds = &upq.ctx.Fields
	grbuild.label = userpreferences.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Theme string `json:"theme,omitempty"`
//	}
//
//	client.UserPreferences.Query().
//		Select(userpreferences.FieldTheme).
//		Scan(ctx, &v)
func (upq *UserPreferencesQuery) Select(fields ...string) *UserPreferencesSelect {
	upq.ctx.Fields = append(upq.ctx.Fields, fields...)
	sbuild := &UserPreferencesSelect{UserPreferencesQuery: upq}
	sbuild.label = userpreferences.Label
	sbuild.flds, sbuild.scan = &upq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserPreferencesSelect configured with the given aggregations.
func (upq *UserPreferencesQuery) Aggregate(fns ...AggregateFunc) *UserPreferencesSelect {
	return upq.Select().Aggregate(fns...)
}

func (upq *UserPreferencesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range upq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, upq); err != nil {
				return err
			}
		}
	}
	for _, f := range upq.ctx.Fields {
		if !userpreferences.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if upq.path != nil {
		prev, err := upq.path(ctx)
		if err != nil {
			return err
		}
		upq.sql = prev
	}
	return nil
}

func (upq *UserPreferencesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserPreferences, error) {
	var (
		nodes       = []*UserPreferences{}
		withFKs     = upq.withFKs
		_spec       = upq.querySpec()
		loadedTypes = [1]bool{
			upq.withUser != nil,
		}
	)
	if upq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, userpreferences.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserPreferences).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserPreferences{config: upq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, upq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := upq.withUser; query != nil {
		if err := upq.loadUser(ctx, query, nodes, nil,
			func(n *UserPreferences, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (upq *UserPreferencesQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserPreferences, init func(*UserPreferences), assign func(*UserPreferences, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*UserPreferences)
	for i := range nodes {
		if nodes[i].user_preferences == nil {
			continue
		}
		fk := *nodes[i].user_preferences
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_preferences" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (upq *UserPreferencesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := upq.querySpec()
	_spec.Node.Columns = upq.ctx.Fields
	if len(upq.ctx.Fields) > 0 {
		_spec.Unique = upq.ctx.Unique != nil && *upq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, upq.driver, _spec)
}

func (upq *UserPreferencesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(userpreferences.Table, userpreferences.Columns, sqlgraph.NewFieldSpec(userpreferences.FieldID, field.TypeUUID))
	_spec.From = upq.sql
	if unique := upq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if upq.path != nil {
		_spec.Unique = true
	}
	if fields := upq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userpreferences.FieldID)
		for i := range fields {
			if fields[i] != userpreferences.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := upq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := upq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := upq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := upq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (upq *UserPreferencesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(upq.driver.Dialect())
	t1 := builder.Table(userpreferences.Table)
	columns := upq.ctx.Fields
	if len(columns) == 0 {
		columns = userpreferences.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if upq.sql != nil {
		selector = upq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if upq.ctx.Unique != nil && *upq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range upq.predicates {
		p(selector)
	}
	for _, p := range upq.order {
		p(selector)
	}
	if offset := upq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := upq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserPreferencesGroupBy is the group-by builder for UserPreferences entities.
type UserPreferencesGroupBy struct {
	selector
	build *UserPreferencesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (upgb *UserPreferencesGroupBy) Aggregate(fns ...AggregateFunc) *UserPreferencesGroupBy {
	upgb.fns = append(upgb.fns, fns...)
	return upgb
}

// Scan applies the selector query and scans the result into the given value.
func (upgb *UserPreferencesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, upgb.build.ctx, ent.OpQueryGroupBy)
	if err := upgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserPreferencesQuery, *UserPreferencesGroupBy](ctx, upgb.build, upgb, upgb.build.inters, v)
}

func (upgb *UserPreferencesGroupBy) sqlScan(ctx context.Context, root *UserPreferencesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(upgb.fns))
	for _, fn := range upgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*upgb.flds)+len(upgb.fns))
		for _, f := range *upgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*upgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := upgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserPreferencesSelect is the builder for selecting fields of UserPreferences entities.
type UserPreferencesSelect struct {
	*UserPreferencesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ups *UserPreferencesSelect) Aggregate(fns ...AggregateFunc) *UserPreferencesSelect {
	ups.fns = append(ups.fns, fns...)
	return ups
}

// Scan applies the selector query and scans the result into the given value.
func (ups *UserPreferencesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ups.ctx, ent.OpQuerySelect)
	if err := ups.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserPreferencesQuery, *UserPreferencesSelect](ctx, ups.UserPreferencesQuery, ups, ups.inters, v)
}

func (ups *UserPreferencesSelect) sqlScan(ctx context.Context, root *UserPreferencesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ups.fns))
	for _, fn := range ups.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ups.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ups.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
