package ports

import (
	"context"
)

// LLMService defines operations for LLM-based text processing
type LLMService interface {
	// GenerateEmbedding generates a vector embedding for the given text
	GenerateEmbedding(ctx context.Context, text string) ([]float32, error)

	// GenerateSummary generates a summary for the given text
	GenerateSummary(ctx context.Context, text string) (string, error)

	// GetEmbeddingDimension returns the dimension of the embeddings generated by this service
	GetEmbeddingDimension() uint64
}
